"""Build, from one guide spec + the keys.json files written at screenshot time:
  docs/clouds/<cloud>.md                                  (the long-form article, images relative to docs/)
  apps/servicehub/src/content/guides/<cloud>.ts           (the same sections for the Help panel)
  apps/servicehub/public/help/<cloud>/*.png               (optimised copies the Help panel serves)
and optimise docs/screenshots/<dir>/*.png in place (256-colour PNG: ~1/3 the size, UI stays crisp)."""
import importlib, json, os, shutil, sys
from PIL import Image
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
cloud = sys.argv[1]
G = importlib.import_module(f"guides.{cloud}")
dirs = G.SHOT_DIRS
keys = {k: json.load(open(f"{ROOT}/docs/screenshots/{d}/keys.json")) for k, d in dirs.items()}

def optimise(path):
    im = Image.open(path)
    if im.mode == "P": return
    im.convert("RGB").quantize(256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE).save(path, optimize=True)

pub = f"{ROOT}/apps/servicehub/public/help/{cloud}"
shutil.rmtree(pub, ignore_errors=True); os.makedirs(pub)
used = []
# Markdown only: the in-app Help article has no `docs/media` to point at, so the video link is not part of INTRO.
WATCH = f"> **Prefer to watch?** A captioned walkthrough of all of Simple mode, about five minutes — including Replay selected, Replay All and the switch to Advanced: [{G.TITLE} video](../media/{cloud}.mp4).\n"
md = [f"# ServiceHub on {G.TITLE} — step by step, with real screenshots\n", WATCH, G.INTRO, "\n---\n"]
ts_sections = []
for part, blurb, steps in G.SECTIONS:
    md.append(f"\n## {part}\n\n*{blurb}*\n")
    ts_steps = []
    for title, text, shots in steps:
        md.append(f"\n### {title}\n\n{text}\n")
        ts_shots = []
        for kind, name in shots:
            d = dirs[kind]; f = f"{ROOT}/docs/screenshots/{d}/{name}.png"
            if not os.path.exists(f): raise SystemExit(f"missing screenshot {f}")
            optimise(f); shutil.copy(f, f"{pub}/{name}.png"); used.append(name)
            k = keys[kind].get(f"{name}.png", [])
            md.append(f"\n![{title} — {name}](../screenshots/{d}/{name}.png)\n")
            if k:
                md.append("\n" + "\n".join(f"{c['n']}. {c['t']}" for c in k) + "\n")
            ts_shots.append({"image": f"/help/{cloud}/{name}.png", "alt": f"{title} ({name})", "keys": [{"n": c["n"], "text": c["t"]} for c in k]})
        ts_steps.append({"title": title, "text": text, "shots": ts_shots})
    ts_sections.append({"part": part, "steps": ts_steps})
md.append("\n---\n\n## If something goes wrong\n\n" + "\n".join(f"- **{q}.** {a}" for q, a in G.TROUBLESHOOTING) + "\n")
md.append("\n## Stopping and cleaning up\n\n" + G.CLEANUP + "\n")
os.makedirs(f"{ROOT}/docs/clouds", exist_ok=True)
open(f"{ROOT}/docs/clouds/{cloud}.md", "w").write("\n".join(md))
os.makedirs(f"{ROOT}/apps/servicehub/src/content/guides", exist_ok=True)
ts = "// GENERATED by scripts/docs-shots/build_guides.py from the guide spec and the screenshots' keys.json — do not edit by hand.\nimport type { Guide } from './types'\n\n"
ts += f"export const {cloud}Guide: Guide = " + json.dumps({"cloud": cloud, "title": G.TITLE, "sections": ts_sections, "troubleshooting": [{"q": q, "a": a} for q, a in G.TROUBLESHOOTING]}, indent=1, ensure_ascii=False) + "\n"
open(f"{ROOT}/apps/servicehub/src/content/guides/{cloud}.generated.ts", "w").write(ts)
print("images", len(used), "→", f"docs/clouds/{cloud}.md")
