// GENERATED by scripts/docs-shots/build_guides.py from the guide spec and the screenshots' keys.json — do not edit by hand.
import type { Guide } from './types'

export const awsGuide: Guide = {
 "cloud": "aws",
 "title": "AWS SQS",
 "sections": [
  {
   "part": "Part 1 — In the AWS console",
   "steps": [
    {
     "title": "1.1 Look at your queues",
     "text": "Sign in to the AWS console, search for **SQS** and open **Queues**. Note the **region** (top right): queues belong to a region, and you will choose the same one in ServiceHub. The **Messages available** column is what ServiceHub will count.",
     "shots": [
      {
       "image": "/help/aws/portal-01-queues.png",
       "alt": "1.1 Look at your queues (portal-01-queues)",
       "keys": [
        {
         "n": 1,
         "text": "Queue names — your orders queue and its dead-letter queue (the one ending -dlq). ServiceHub finds every queue in the region; you do not list them."
        },
        {
         "n": 2,
         "text": "Messages available — waiting to be received. The dead-letter queue's number is what ServiceHub counts as dead letters (here 324)."
        },
        {
         "n": 3,
         "text": "Region — queues belong to a region. You choose the same region in ServiceHub when you connect (here Asia Pacific (Mumbai), ap-south-1)."
        }
       ]
      }
     ]
    },
    {
     "title": "1.2 Find the dead-letter queue",
     "text": "Open your main queue and choose the **Dead-letter queue** tab. It names the queue that receives failures and the **Maximum receives** — how many tries before SQS moves a message there. If a queue has no dead-letter queue, failed messages are retried until they expire and ServiceHub has nothing to show.",
     "shots": [
      {
       "image": "/help/aws/portal-02-orders-queue.png",
       "alt": "1.2 Find the dead-letter queue (portal-02-orders-queue)",
       "keys": [
        {
         "n": 1,
         "text": "URL — the address of this queue. ServiceHub builds it for you from the queue's name and your region."
        },
        {
         "n": 2,
         "text": "Dead-letter queue — Enabled: a message that fails too often is moved to a second queue instead of being lost."
        },
        {
         "n": 3,
         "text": "Dead-letter queue tab — shows which queue receives the failures (next screenshot)."
        }
       ]
      },
      {
       "image": "/help/aws/portal-03-dead-letter-queue.png",
       "alt": "1.2 Find the dead-letter queue (portal-03-dead-letter-queue)",
       "keys": [
        {
         "n": 1,
         "text": "Queue — the dead-letter queue that receives the failures. ServiceHub reads this one to show Dead letters."
        },
        {
         "n": 2,
         "text": "Maximum receives — 3: after three failed tries SQS moves the message here. Reading a dead letter from ServiceHub counts as one more receive, which is why ServiceHub only looks when you ask."
        }
       ]
      }
     ]
    },
    {
     "title": "1.3 Create a ServiceHub-only user",
     "text": "Open **IAM → Users → Create user**. Name it (we use `servicehub-app`), leave **console access** off — it is for programs only — and give it no groups. Do not use your own user or the root account: a separate user can be switched off later without disturbing anything else.",
     "shots": [
      {
       "image": "/help/aws/portal-04-iam-users.png",
       "alt": "1.3 Create a ServiceHub-only user (portal-04-iam-users)",
       "keys": [
        {
         "n": 1,
         "text": "Create user — start here to make a user just for ServiceHub, not your own."
        },
        {
         "n": 2,
         "text": "The ServiceHub user — separate from your own, so you can switch it off later without disturbing anything else."
        }
       ]
      }
     ]
    },
    {
     "title": "1.4 Give it only the SQS permissions it needs",
     "text": "On the user, **Add permissions → Create inline policy**, choose JSON, and paste the policy from the start of this guide with your queue names. The user then has exactly one policy, limited to your queues: if its key ever leaked, it could touch nothing else in your account.",
     "shots": [
      {
       "image": "/help/aws/portal-05-user-permissions.png",
       "alt": "1.4 Give it only the SQS permissions it needs (portal-05-user-permissions)",
       "keys": [
        {
         "n": 1,
         "text": "Console access — Disabled. This user is for programs only: nobody can sign in to the AWS console as it."
        },
        {
         "n": 2,
         "text": "Access key 1 — what ServiceHub signs in with. It is made on the Security credentials tab; AWS shows its secret only once."
        },
        {
         "n": 3,
         "text": "servicehub-sqs — one inline policy, limited to the two queues (next screenshot). The user has no other permissions."
        }
       ]
      },
      {
       "image": "/help/aws/portal-06-policy-json.png",
       "alt": "1.4 Give it only the SQS permissions it needs (portal-06-policy-json)",
       "keys": [
        {
         "n": 1,
         "text": "Actions — what ServiceHub may do: read queue counts, receive (to look), change visibility (to hand a looked-at message back), send and delete (to replay). Above these, sqs:ListQueues lets it find your queues."
        },
        {
         "n": 2,
         "text": "Resource — only these two queues. If the key ever leaked, it could touch nothing else in your account."
        }
       ]
      }
     ]
    },
    {
     "title": "1.5 Create an access key",
     "text": "Open the user's **Security credentials** tab and choose **Create access key**. Pick **Application running outside AWS**, then copy the **Access key ID** and the **Secret access key** — AWS shows the secret **once**. Treat both like a password: ServiceHub encrypts them on arrival and never shows them again. Making the key inactive or deleting it is how you revoke access later.",
     "shots": [
      {
       "image": "/help/aws/portal-07-access-keys.png",
       "alt": "1.5 Create an access key (portal-07-access-keys)",
       "keys": [
        {
         "n": 1,
         "text": "Create access key — choose “Application running outside AWS”, then copy the Access key ID and the Secret access key. AWS shows the secret once."
        },
        {
         "n": 2,
         "text": "Status — Active. Make it Inactive or delete it at any time to cut ServiceHub off."
        },
        {
         "n": 3,
         "text": "Actions — make the key inactive or delete it: the way to revoke ServiceHub’s access later."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 2 — Connect AWS in ServiceHub",
   "steps": [
    {
     "title": "2.1 The welcome page",
     "text": "With no cloud connected, ServiceHub opens on a welcome page. Choose **Connect AWS**.",
     "shots": [
      {
       "image": "/help/aws/01-welcome.png",
       "alt": "2.1 The welcome page (01-welcome)",
       "keys": [
        {
         "n": 1,
         "text": "Connect AWS — opens the Add a cloud window on the AWS tab. It asks for an access key and a region; nothing is read until you press Connect there."
        },
        {
         "n": 2,
         "text": "Add a cloud — the same window, from anywhere in the app. Use it later to connect Azure or Google Cloud as well."
        },
        {
         "n": 3,
         "text": "Simple | Advanced — Simple is where you act. Advanced is read-only pages (ledger, signatures, agents); it never changes anything."
        },
        {
         "n": 4,
         "text": "Help — opens the Help panel with task-shaped answers and the keyboard shortcuts."
        },
        {
         "n": 5,
         "text": "Connect Azure / Connect Google — the same Add a cloud window, on the Azure or Google Cloud tab. You do not need them for AWS."
        }
       ]
      }
     ]
    },
    {
     "title": "2.2 Add a cloud",
     "text": "The window opens on the AWS tab. Open **Where do I get the AWS access key?** for the same console steps you just did.",
     "shots": [
      {
       "image": "/help/aws/02-add-cloud.png",
       "alt": "2.2 Add a cloud (02-add-cloud)",
       "keys": [
        {
         "n": 1,
         "text": "Cloud tabs — AWS SQS / SNS is selected. The Azure and Google tabs ask for different credentials."
        },
        {
         "n": 2,
         "text": "Where do I get the AWS access key? — expands the console steps, with the permissions to give."
        },
        {
         "n": 3,
         "text": "Name — what you will see in ServiceHub. It is a label only; it does not change anything in AWS."
        },
        {
         "n": 4,
         "text": "Environment — Development, UAT or Production. Start with Development; Auto Replay never acts in Production."
        },
        {
         "n": 5,
         "text": "Access key ID — the ID of the access key you made for ServiceHub (it starts AKIA)."
        },
        {
         "n": 6,
         "text": "Secret access key — shown by AWS only once, when you create the key. It is encrypted on this server and never shown again."
        },
        {
         "n": 7,
         "text": "Show value — reveals what you typed so you can check it. It cannot reveal a stored secret."
        },
        {
         "n": 8,
         "text": "Region — the region your queues are in (the console shows it top right). Queues in other regions are not seen."
        },
        {
         "n": 9,
         "text": "The permissions ServiceHub uses — to watch, and (in the second sentence) also to replay. Give it nothing more."
        },
        {
         "n": 10,
         "text": "(?) — opens Help on this very screen. Every window has one."
        },
        {
         "n": 11,
         "text": "✕ — closes the window without saving (Esc does the same)."
        }
       ]
      },
      {
       "image": "/help/aws/02-add-cloud-help.png",
       "alt": "2.2 Add a cloud (02-add-cloud-help)",
       "keys": [
        {
         "n": 1,
         "text": "IAM → Users — in the AWS console, make a user just for ServiceHub (not your own)."
        },
        {
         "n": 2,
         "text": "Attach a policy with only the SQS permissions below, limited to the queues you want watched."
        },
        {
         "n": 3,
         "text": "Security credentials → Create access key — copy the Access key ID and the Secret access key; AWS shows the secret once."
        },
        {
         "n": 4,
         "text": "Use the region your queues are in."
        },
        {
         "n": 5,
         "text": "The form underneath — the cloud tabs, Name, Environment, Access key ID, Secret access key, Show value and Region, exactly as in the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "2.3 Fill it in and connect",
     "text": "Give it a name, keep the environment as **Development** for your first connection, paste the Access key ID and the Secret access key, choose the region your queues are in, and press **Connect**. ServiceHub tests the key, then saves it encrypted (AES-256-GCM).",
     "shots": [
      {
       "image": "/help/aws/03-add-cloud-filled.png",
       "alt": "2.3 Fill it in and connect (03-add-cloud-filled)",
       "keys": [
        {
         "n": 1,
         "text": "A name you will recognise."
        },
        {
         "n": 2,
         "text": "The Access key ID (AWS’s documented example is shown here, not a real key)."
        },
        {
         "n": 3,
         "text": "The Secret access key, hidden as you paste it."
        },
        {
         "n": 4,
         "text": "The region — here ap-south-1, Asia Pacific (Mumbai)."
        },
        {
         "n": 5,
         "text": "The rest of the form above — cloud tabs, Environment and Show value, as described on the previous screenshot."
        },
        {
         "n": 6,
         "text": "Cancel and Connect — shown in full on the next screenshot."
        }
       ]
      },
      {
       "image": "/help/aws/03b-add-cloud-bottom.png",
       "alt": "2.3 Fill it in and connect (03b-add-cloud-bottom)",
       "keys": [
        {
         "n": 1,
         "text": "The permissions ServiceHub uses — to watch, and (second sentence) also to replay. Give it nothing more."
        },
        {
         "n": 2,
         "text": "Cancel — closes the window; nothing is saved."
        },
        {
         "n": 3,
         "text": "Connect — tests the key, then saves it. It only reads queue counts; it never receives, sends or deletes anything by itself."
        },
        {
         "n": 4,
         "text": "Region — ap-south-1 (Asia Pacific, Mumbai) is chosen here."
        },
        {
         "n": 5,
         "text": "The fields above — the name, key ID, secret and Show value, as filled in on the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "2.4 The result",
     "text": "You see exactly what ServiceHub can see: how many queues it found, how many messages are dead-lettered right now, and that this cloud **cannot yet prove a replayed message stayed fixed** — ServiceHub will say so honestly rather than pretend.",
     "shots": [
      {
       "image": "/help/aws/04-connected.png",
       "alt": "2.4 The result (04-connected)",
       "keys": [
        {
         "n": 1,
         "text": "The result: how many queues ServiceHub found, how many messages are dead-lettered right now, and whether this cloud can prove a replayed message stayed fixed (AWS cannot yet — it will say so honestly)."
        },
        {
         "n": 2,
         "text": "Open Home — closes the window and shows Home."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 3 — Learn the screens",
   "steps": [
    {
     "title": "3.1 Home",
     "text": "Home answers: *what needs me* and *how is each cloud doing*. For AWS it shows what the cloud can do (count messages, record dead letters when you look), the **Look now** button, and the counts. Scroll down for why messages failed, how replays ended, the queues needing attention, the latest dead letters and a live activity list.",
     "shots": [
      {
       "image": "/help/aws/05-home.png",
       "alt": "3.1 Home (05-home)",
       "keys": [
        {
         "n": 1,
         "text": "Window — the period Home counts over (24 hours, 7 or 30 days). It changes what you see, never what happens."
        },
        {
         "n": 2,
         "text": "Connected, and the region — ServiceHub can reach AWS with your key; the region is the one you chose."
        },
        {
         "n": 3,
         "text": "What this cloud can do — ticks show what AWS lets ServiceHub do safely. AWS counts messages and records dead letters when you look; it cannot browse active messages or prove a fix held."
        },
        {
         "n": 4,
         "text": "Look now — asks AWS for its dead letters (up to 100 per queue) and keeps them in ServiceHub. Each one read counts as one delivery attempt, which is why ServiceHub never does it on its own."
        },
        {
         "n": 5,
         "text": "Dead letters — opens the list of messages that failed and were set aside."
        },
        {
         "n": 6,
         "text": "Active messages — on AWS this shows counts per queue only; opening a message there would count as a delivery."
        },
        {
         "n": 7,
         "text": "Replayed — everything put back, by whom, and how it went."
        },
        {
         "n": 8,
         "text": "Auto Replay rules — opens the rules panel. On AWS a rule always waits for a person, because AWS cannot prove a fix held."
        },
        {
         "n": 9,
         "text": "Got it — hides this explanation. It does not affect your data."
        },
        {
         "n": 10,
         "text": "See all dead letters in AWS — opens the Dead letters list for this cloud."
        },
        {
         "n": 11,
         "text": "Help for this page (the book beside the title) — opens Help on this very page, over it. Every page has one."
        }
       ]
      },
      {
       "image": "/help/aws/05c-home-middle.png",
       "alt": "3.1 Home (05c-home-middle)",
       "keys": [
        {
         "n": 1,
         "text": "Why messages failed — the reasons among the dead letters ServiceHub has recorded, biggest first, with how many each has. It only counts what you have looked at."
        },
        {
         "n": 2,
         "text": "How replays ended — what happened to the replays in this window. On AWS they stay “watching”, because AWS cannot prove a fix held."
        },
        {
         "n": 3,
         "text": "Queues and topics needing attention — the queues with the most dead letters first. Open → shows that queue’s dead letters."
        },
        {
         "n": 4,
         "text": "Latest recorded dead letters — the five most recent ServiceHub has recorded, each with Details →. “See all →” opens the full list."
        },
        {
         "n": 5,
         "text": "Recent activity — shown in full on the next screenshot."
        }
       ]
      },
      {
       "image": "/help/aws/05d-home-end.png",
       "alt": "3.1 Home (05d-home-end)",
       "keys": [
        {
         "n": 1,
         "text": "The five latest dead letters, each with Details → — the same message view as on the Dead letters tab."
        },
        {
         "n": 2,
         "text": "Recent activity — what ServiceHub and people did, newest first (Live means it updates by itself). Each line opens to show its detail; nothing here changes anything."
        },
        {
         "n": 3,
         "text": "Each reason in “Why messages failed” is a link that opens the Dead letters list filtered to that reason; Open → opens that queue’s dead letters."
        }
       ]
      }
     ]
    },
    {
     "title": "3.2 The bar and the sidebar",
     "text": "These are the same on every page.",
     "shots": [
      {
       "image": "/help/aws/05b-navigation.png",
       "alt": "3.2 The bar and the sidebar (05b-navigation)",
       "keys": [
        {
         "n": 1,
         "text": "Back — returns to the previous place in the app."
        },
        {
         "n": 2,
         "text": "Forward — goes to the place you came back from."
        },
        {
         "n": 3,
         "text": "Search (⌘K) — jump to a cloud, queue or page. Searching never changes anything."
        },
        {
         "n": 4,
         "text": "The bell — the only place the Agent asks you something. A number appears when it needs you."
        },
        {
         "n": 5,
         "text": "Simple — the two pages where you do the work."
        },
        {
         "n": 6,
         "text": "Advanced — four read-only pages."
        },
        {
         "n": 7,
         "text": "You — who ServiceHub records actions as, with your role."
        },
        {
         "n": 8,
         "text": "Dead letters — messages that failed, with the reason and a Replay button."
        },
        {
         "n": 9,
         "text": "Active messages — what is waiting now, counted per queue on AWS."
        },
        {
         "n": 10,
         "text": "Replayed — what was put back and whether it stayed fixed."
        },
        {
         "n": 11,
         "text": "Auto Replay — rules for retries ServiceHub may do on its own."
        },
        {
         "n": 12,
         "text": "Your cloud — pick it to see only that cloud. The dot shows the connection is healthy."
        },
        {
         "n": 13,
         "text": "Connections — your connected clouds, to test or remove."
        },
        {
         "n": 14,
         "text": "Add a cloud — connect another cloud."
        },
        {
         "n": 15,
         "text": "Settings — connections, notifications, preferences, access and backup."
        },
        {
         "n": 16,
         "text": "Help — answers and shortcuts."
        },
        {
         "n": 17,
         "text": "Home — the overview: what needs attention, what the Agent is doing, and how replays ended."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 4 — Work with dead letters",
   "steps": [
    {
     "title": "4.1 The Dead letters tab",
     "text": "A **dead letter** is a message your consumer failed to process several times, so SQS moved it to the dead-letter queue. The list starts **empty on AWS** even when the queue holds thousands, because reading a dead letter counts as a delivery attempt. Press **Look at AWS's dead letters now**: ServiceHub receives up to 100 per queue, records them, and hands them straight back. It never deletes or moves anything. Press it again to record more; AWS hands back a sample, so a dead letter not seen on a later look stays in the list.",
     "shots": [
      {
       "image": "/help/aws/06-dead-letters.png",
       "alt": "4.1 The Dead letters tab (06-dead-letters)",
       "keys": [
        {
         "n": 1,
         "text": "Namespace picker — all of AWS, or one account and region."
        },
        {
         "n": 2,
         "text": "Why the list starts empty — on AWS, reading a dead letter counts as one delivery attempt, so ServiceHub only looks when you ask. It reads up to 100 per queue and keeps them here."
        },
        {
         "n": 3,
         "text": "Look at AWS’s dead letters now — receives up to 100 dead letters per queue, records them, and hands them straight back. It never deletes or moves anything; it does add one to each message’s delivery count."
        },
        {
         "n": 4,
         "text": "The empty list — “nothing recorded” does not mean there are none: the queue holds 324. Press Look now to see them."
        },
        {
         "n": 5,
         "text": "Help for this page — opens Help on this page’s step of the guide. The (?) beside it only re-shows the short explanation."
        },
        {
         "n": 6,
         "text": "The three tabs — Dead letters, Active and Replayed — switch the list below. The (?) beside the title brings back the short “What you’re looking at” card."
        },
        {
         "n": 7,
         "text": "Filters and Refresh — Showing, Time window, queue or topic and search narrow the list; Refresh re-reads what ServiceHub has recorded. On AWS Refresh does not look at AWS: only Look now does."
        }
       ]
      },
      {
       "image": "/help/aws/06b-after-look.png",
       "alt": "4.1 The Dead letters tab (06b-after-look)",
       "keys": [
        {
         "n": 1,
         "text": "What the look found — when it ran, how many queues had dead letters, and how many new ones were recorded."
        },
        {
         "n": 2,
         "text": "AWS hands back a sample, not the whole queue: a dead letter recorded earlier and not seen this time stays in the list; it is not assumed gone."
        },
        {
         "n": 3,
         "text": "Why they failed — the biggest reasons among the dead letters recorded, counted."
        },
        {
         "n": 4,
         "text": "Dead letters tab — the number is how many ServiceHub has recorded (not how many AWS holds)."
        },
        {
         "n": 5,
         "text": "Look again — records any dead letters not seen before. Each look adds one delivery attempt to the messages it reads."
        },
        {
         "n": 6,
         "text": "Reason chips — click one to show only that reason."
        },
        {
         "n": 7,
         "text": "The namespace picker, the (?) that re-shows the short explanation, and the Active and Replayed tabs."
        },
        {
         "n": 8,
         "text": "Filters, Replay All Messages and Refresh — described on the next screenshot, where the table is in view."
        },
        {
         "n": 9,
         "text": "The selection bar — the tick selects the whole page; View details chooses columns; Replay selected stays dimmed until something is ticked."
        },
        {
         "n": 10,
         "text": "The tick in the table heading — ticks every row on this page."
        },
        {
         "n": 11,
         "text": "The table headings — each has an ⓘ that explains that column in a sentence; the next screenshot shows the table itself."
        }
       ]
      }
     ]
    },
    {
     "title": "4.2 Filters, selection and the table",
     "text": "Narrow the list, tick the messages you want, and use **Details** or **Replay** on a row. Choosing a reason chip filters to that reason (with *show all reasons* at the foot to clear it, and *Select all* for that reason in the selection bar); the list pages at the bottom. Refresh re-reads what ServiceHub has recorded; only Look now asks AWS.",
     "shots": [
      {
       "image": "/help/aws/07-filters-and-table.png",
       "alt": "4.2 Filters, selection and the table (07-filters-and-table)",
       "keys": [
        {
         "n": 1,
         "text": "Showing — Stuck now, or messages that have since left the queue."
        },
        {
         "n": 2,
         "text": "Time window — only messages set aside in this period."
        },
        {
         "n": 3,
         "text": "Search — by message ID, queue, reason or error text."
        },
        {
         "n": 4,
         "text": "Replay All Messages — opens a preview of every message still stuck in the cloud and namespace you are viewing. It ignores the filters, time window and search here. Nothing is sent until you confirm the preview."
        },
        {
         "n": 5,
         "text": "Refresh — reads the queue again. It re-reads what ServiceHub has already recorded; it does not look at AWS (only Look now does). The ⓘ beside it says when it was last updated."
        },
        {
         "n": 6,
         "text": "Selection — tick rows to act on several; this line shows how many."
        },
        {
         "n": 7,
         "text": "Replay selected — opens the same preview for just the ticked messages."
        },
        {
         "n": 8,
         "text": "Details — opens the message: why it failed, its body, properties and delivery history."
        },
        {
         "n": 9,
         "text": "Replay — opens the proposal for this one message. It does not send anything yet."
        },
        {
         "n": 10,
         "text": "The table — a tick on every row (the one in the heading ticks the whole page), Details and Replay on every row, and an ⓘ About button on each column heading that explains that column in a sentence. “View details” in the heading chooses which columns show."
        },
        {
         "n": 11,
         "text": "Reason chips — each shows a reason and how many messages have it. Click one to show only those; click it again to show all."
        },
        {
         "n": 12,
         "text": "All queues & topics — limit the list to one queue or topic."
        },
        {
         "n": 13,
         "text": "The selection bar — the tick selects every row on this page; View details chooses which columns show; Replay selected stays dimmed until something is ticked."
        },
        {
         "n": 14,
         "text": "Look at AWS’s dead letters now — records any dead letters not seen before. Each look adds one delivery attempt to the messages it reads."
        }
       ]
      },
      {
       "image": "/help/aws/07a-reason-filter.png",
       "alt": "4.2 Filters, selection and the table (07a-reason-filter)",
       "keys": [
        {
         "n": 1,
         "text": "Filtering by a reason — the chosen reason is highlighted and “show all reasons” clears the filter. The list below shows only that reason."
        },
        {
         "n": 2,
         "text": "The reason chips — click one to show only that reason."
        },
        {
         "n": 3,
         "text": "The namespace picker, the (?) that re-shows the short explanation, and the three tabs."
        },
        {
         "n": 4,
         "text": "Filters, Replay All Messages, Refresh and Look now — described on the earlier screenshots."
        },
        {
         "n": 5,
         "text": "The selection bar (which now offers “Select all” for this reason), the table headings and the rows, as on the earlier screenshots."
        }
       ]
      },
      {
       "image": "/help/aws/07a-reason-filter-end.png",
       "alt": "4.2 Filters, selection and the table (07a-reason-filter-end)",
       "keys": [
        {
         "n": 1,
         "text": "Show all reasons — at the foot of a filtered list too: clears the reason filter and brings every recorded dead letter back."
        },
        {
         "n": 2,
         "text": "The rows of this reason only, and the selection bar repeated underneath."
        },
        {
         "n": 3,
         "text": "Paging — rows per page, previous, the page numbers and next."
        }
       ]
      },
      {
       "image": "/help/aws/07c-table-end.png",
       "alt": "4.2 Filters, selection and the table (07c-table-end)",
       "keys": [
        {
         "n": 1,
         "text": "The foot of the table — the same ticks, Details and Replay on every row, and the selection bar repeated underneath."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next. The list holds up to 100 dead letters per queue from each look."
        }
       ]
      },
      {
       "image": "/help/aws/07b-selection.png",
       "alt": "4.2 Filters, selection and the table (07b-selection)",
       "keys": [
        {
         "n": 1,
         "text": "Row tick — choose which messages to act on. The header tick chooses every row on the page."
        },
        {
         "n": 2,
         "text": "Selection count — how many messages are ticked."
        },
        {
         "n": 3,
         "text": "Clear — unticks everything. Nothing else changes."
        },
        {
         "n": 4,
         "text": "Replay selected — opens the bulk preview for just these messages. Nothing is sent yet."
        },
        {
         "n": 5,
         "text": "The filter row — reason chips, Showing, Time window, queue, search, Replay All Messages and Refresh, each explained on the previous screenshot."
        },
        {
         "n": 6,
         "text": "The table — the ticks, Details and Replay on every row, and the whole-page tick in the heading."
        },
        {
         "n": 7,
         "text": "The selection bar — the whole-page tick and View details (which columns show)."
        }
       ]
      }
     ]
    },
    {
     "title": "4.3 Open a message",
     "text": "**Details** opens the message: the reason, a plain-words reading of why it failed (marked *Suggestion* because it is a reading, not something AWS reported), and the body. The tabs show the body, the attributes your sender attached, what SQS recorded, and the delivery count — which includes ServiceHub's own looks. At the bottom are **Replay this message** and **Purge instead…**, which only opens a form.",
     "shots": [
      {
       "image": "/help/aws/08-message-details.png",
       "alt": "4.3 Open a message (08-message-details)",
       "keys": [
        {
         "n": 1,
         "text": "Expand — widens the panel for long messages."
        },
        {
         "n": 2,
         "text": "Overview — reason, why it failed, the body with the bad field marked."
        },
        {
         "n": 3,
         "text": "Delivery — how many times the message was received (ServiceHub’s own looks count) and when AWS set it aside."
        },
        {
         "n": 4,
         "text": "Why it failed — a plain-words reading of the recorded reason. Marked Suggestion: it is a reading, not something AWS reported."
        },
        {
         "n": 5,
         "text": "Formatted / Raw — switch the body view."
        },
        {
         "n": 6,
         "text": "Replay this message — opens the proposal. Nothing is sent from here."
        },
        {
         "n": 7,
         "text": "Body, Properties and Headers — the other tabs; each is shown below."
        },
        {
         "n": 8,
         "text": "Formatted and Copy body — pretty-print the body, or copy it to your clipboard. The copy stays in your browser."
        },
        {
         "n": 9,
         "text": "Copy message ID — copies the ID so you can search for it elsewhere."
        }
       ]
      },
      {
       "image": "/help/aws/08b-message-details-end.png",
       "alt": "4.3 Open a message (08b-message-details-end)",
       "keys": [
        {
         "n": 1,
         "text": "Replay this message — opens the proposal. Nothing is sent from here."
        },
        {
         "n": 2,
         "text": "Purge instead… — for a message not worth replaying. It only opens a small form: you give a reason, and nothing is deleted until you press “Purge for good”. Deleting is permanent, goes through the same checks as a replay, and is recorded with your name and reason."
        },
        {
         "n": 3,
         "text": "Expand, the body view and the copy buttons — as on the previous screenshots."
        }
       ]
      },
      {
       "image": "/help/aws/08-message-details-body.png",
       "alt": "4.3 Open a message (08-message-details-body)",
       "keys": [
        {
         "n": 1,
         "text": "The message body exactly as it was sent."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        },
        {
         "n": 3,
         "text": "Formatted / Raw switch the view; Copy body copies it to your clipboard."
        }
       ]
      },
      {
       "image": "/help/aws/08-message-details-properties.png",
       "alt": "4.3 Open a message (08-message-details-properties)",
       "keys": [
        {
         "n": 1,
         "text": "The message attributes the sender attached (for example shs-error-type) and the SQS system attributes."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      },
      {
       "image": "/help/aws/08-message-details-headers.png",
       "alt": "4.3 Open a message (08-message-details-headers)",
       "keys": [
        {
         "n": 1,
         "text": "What SQS recorded: the sent time, the first receive time, how many times it was received, and which queue it was dead-lettered from."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      },
      {
       "image": "/help/aws/08-message-details-delivery.png",
       "alt": "4.3 Open a message (08-message-details-delivery)",
       "keys": [
        {
         "n": 1,
         "text": "How many times AWS delivered it before setting it aside. ServiceHub’s own looks are counted in this number."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      }
     ]
    },
    {
     "title": "4.4 Replay one message — you see the proposal first",
     "text": "**Replay** never sends straight away. It shows what will happen (the message goes back to the queue it came from and the dead-letter copy is removed once AWS accepts the new one), every safety check, and what happens afterwards. Only the blue button sends.",
     "shots": [
      {
       "image": "/help/aws/09-replay-proposal.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal)",
       "keys": [
        {
         "n": 1,
         "text": "The message — what is about to be replayed: ID, where it is stuck, when and why it was set aside, and its body."
        },
        {
         "n": 2,
         "text": "Replay 1 message — sends it back. It is only sent when you press this."
        },
        {
         "n": 3,
         "text": "What will happen, Safety checks, After it runs — fold open or closed; the next screenshot shows them open."
        },
        {
         "n": 4,
         "text": "Cancel — closes without sending."
        }
       ]
      },
      {
       "image": "/help/aws/09-replay-proposal-middle.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal-middle)",
       "keys": [
        {
         "n": 1,
         "text": "The four sections of the proposal — The message, What will happen, Safety checks and After it runs. Each folds open or closed; nothing here sends anything."
        },
        {
         "n": 2,
         "text": "Replay 1 message sends it; Cancel closes without sending. Both are repeated at the foot of the window so they are always in reach."
        }
       ]
      },
      {
       "image": "/help/aws/09-replay-proposal-checks.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal-checks)",
       "keys": [
        {
         "n": 1,
         "text": "What will happen — where it goes and what happens to the dead-letter copy (it is removed once AWS accepts the new copy)."
        },
        {
         "n": 2,
         "text": "Safety checks — every check that must pass; a failing one blocks the replay and says why."
        },
        {
         "n": 3,
         "text": "After it runs — ServiceHub records it and watches for 24 hours; if it comes back, nothing retries it."
        },
        {
         "n": 4,
         "text": "Cancel — closes without sending."
        },
        {
         "n": 5,
         "text": "The folding headings and the Replay button repeated at the end of the window."
        }
       ]
      }
     ]
    },
    {
     "title": "4.5 Replay several at once",
     "text": "Tick messages (or use **Replay All Messages**) to get a preview: how many will be replayed, which are held back by a safety check, grouped by how they failed and where each goes. When the failures look like bad data, it suggests replaying one first. They are sent one at a time, each re-checked, and the run stops by itself after five sends in a row that are not accepted. Further down is **Purge instead…** — a separate, deliberate step to delete messages that are not worth replaying.",
     "shots": [
      {
       "image": "/help/aws/13-bulk-replay.png",
       "alt": "4.5 Replay several at once (13-bulk-replay)",
       "keys": [
        {
         "n": 1,
         "text": "Preview — nothing has run yet. Step 1 of Preview → Run → Watch."
        },
        {
         "n": 2,
         "text": "Held back — messages that fail a safety check stay in dead letters; they are never forced."
        },
        {
         "n": 3,
         "text": "Grouped by how they failed — so you can see whether you are fixing one problem or several."
        },
        {
         "n": 4,
         "text": "Where each one goes — the queue each message will be sent back to."
        },
        {
         "n": 5,
         "text": "Replay N messages — sends them one at a time, re-checking each. You can stop partway."
        },
        {
         "n": 6,
         "text": "Cancel — nothing is sent."
        },
        {
         "n": 7,
         "text": "A warning when the failures look like bad data — Replay one first? sends a sample of one, so you can see whether it holds before sending the rest."
        },
        {
         "n": 8,
         "text": "Page controls — move through the list when more messages are chosen than fit on one page."
        }
       ]
      },
      {
       "image": "/help/aws/13b-bulk-replay-end.png",
       "alt": "4.5 Replay several at once (13b-bulk-replay-end)",
       "keys": [
        {
         "n": 1,
         "text": "How it will run — the pace (a few messages a second, gentle on your consumer) and the automatic stop: five sends in a row that are not accepted."
        },
        {
         "n": 2,
         "text": "After they are sent back — folds open to say what ServiceHub does next: it keeps watching, and on AWS it records each one as “verification required”, never as fixed."
        },
        {
         "n": 3,
         "text": "Purge instead… — for messages not worth replaying. It does not delete anything yet: it opens a separate step that asks why, shows what would be purged, and needs you to type a confirmation. Deleting is for good, and each purge is recorded with your name and reason."
        },
        {
         "n": 4,
         "text": "Page controls — move through the list when more messages are chosen than fit on one page."
        },
        {
         "n": 5,
         "text": "Replay N messages — sends them one at a time, re-checking each. You can stop partway."
        },
        {
         "n": 6,
         "text": "Cancel — nothing is sent."
        }
       ]
      }
     ]
    },
    {
     "title": "4.6 The result",
     "text": "ServiceHub says plainly what happened and records it under Replayed. On AWS the result will read **Verification required**: the message was sent back, but AWS cannot prove the dead-letter queue stayed empty, so ServiceHub never says it held. If a consumer is running on the queue it may pick the message up straight away.",
     "shots": [
      {
       "image": "/help/aws/10-replay-result.png",
       "alt": "4.6 The result (10-replay-result)",
       "keys": [
        {
         "n": 1,
         "text": "The result, in plain words: it was sent back, and ServiceHub will watch for it coming back."
        },
        {
         "n": 2,
         "text": "It is recorded, with who did it, and shows under Replayed (and in Advanced → Recovery Ledger). On AWS the result will read “Verification required”: this cloud cannot prove the queue stayed empty, so ServiceHub never says it held."
        },
        {
         "n": 3,
         "text": "Done — closes the window."
        },
        {
         "n": 4,
         "text": "Active messages / Replayed — jump to where you can watch this message."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 5 — Afterwards",
   "steps": [
    {
     "title": "5.1 Replayed",
     "text": "Every replay, who did it, and how it ended. On AWS a replay stays *Watching* for its window and is then recorded as *verification required* — never as success — until a person judges it.",
     "shots": [
      {
       "image": "/help/aws/11-replayed.png",
       "alt": "5.1 Replayed (11-replayed)",
       "keys": [
        {
         "n": 1,
         "text": "Messages replayed — how many were put back in the window."
        },
        {
         "n": 2,
         "text": "Being watched — replays still inside their watch window. AWS cannot prove whether each stayed fixed, so they wait for you to judge."
        },
        {
         "n": 3,
         "text": "Came back — messages that failed the same way again. Nothing retries them on its own."
        },
        {
         "n": 4,
         "text": "Result filter — stayed fixed, being watched, came back."
        },
        {
         "n": 5,
         "text": "Download — saves this list as a file. It does not change anything."
        },
        {
         "n": 6,
         "text": "Details — the full record of this replay."
        },
        {
         "n": 7,
         "text": "Filters — namespace, queue or topic, result, time window and search; Refresh reads the list again. They change what is listed, never what happened."
        },
        {
         "n": 8,
         "text": "The table — a tick per replay (the heading tick ticks the page) and Details on each row."
        },
        {
         "n": 9,
         "text": "What am I looking at? — a short reading guide. Auto Replay rules — opens the rules page. All and Last 24 hours — the result and time filters."
        },
        {
         "n": 10,
         "text": "The three tabs — Dead letters, Active and Replayed. They switch the list below without leaving the page."
        }
       ]
      },
      {
       "image": "/help/aws/11b-replayed-end.png",
       "alt": "5.1 Replayed (11b-replayed-end)",
       "keys": [
        {
         "n": 1,
         "text": "The replays, newest first — each with a tick and Details."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next."
        },
        {
         "n": 3,
         "text": "Filters — result, queue or topic, who replayed it, time window and search; Refresh re-reads the list and Download as CSV saves it as a file. They change what is listed, never what happened."
        },
        {
         "n": 4,
         "text": "The three tabs, the Auto Replay rules button and the table headings, as on the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "5.2 Active messages",
     "text": "What is waiting right now, **counted per queue**. ServiceHub does not open active messages on AWS, because there is no way to look at one without it counting as a delivery — watching could push a message into the dead-letter queue by itself. For the same reason **Follow live** is not offered here. **Send a message** is the one control here that changes a queue.",
     "shots": [
      {
       "image": "/help/aws/12-active.png",
       "alt": "5.2 Active messages (12-active)",
       "keys": [
        {
         "n": 1,
         "text": "Send a message — puts a test message on a queue. This does change the queue, so use a dev queue."
        },
        {
         "n": 2,
         "text": "Why there is no message list — on AWS there is no way to look at a message without it counting as a delivery, and watching could push it into the dead-letter queue by itself. So ServiceHub shows counts per queue, and “Follow live” is not offered."
        },
        {
         "n": 3,
         "text": "Namespace — all of AWS, or one account and region."
        },
        {
         "n": 4,
         "text": "The three tabs — Dead letters, Active and Replayed — each with an ⓘ that explains it."
        },
        {
         "n": 5,
         "text": "The table — one row per queue found in this region, including the dead-letter queue itself: Queue or topic, Waiting now (ready to be received) and Dead-lettered (moved here after failing too often). AWS counts them; ServiceHub never opens them. The ⓘ on each heading says what that count means."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 6 — Auto Replay",
   "steps": [
    {
     "title": "6.1 Rules",
     "text": "A rule names a failure ServiceHub has already seen and how carefully to retry it. It never runs in Production, goes through the same safety checks as you, and **stops itself** if fewer than half of its replays stay fixed. On AWS a rule always waits for a person, because AWS cannot prove a fix held.",
     "shots": [
      {
       "image": "/help/aws/14-auto-replay.png",
       "alt": "6.1 Rules (14-auto-replay)",
       "keys": [
        {
         "n": 1,
         "text": "Auto Generate Rules — proposes rules from failures already seen. It only proposes; you decide what to turn on."
        },
        {
         "n": 2,
         "text": "Create rule — start a rule from a failure you have already seen."
        },
        {
         "n": 3,
         "text": "How it works — you name a failure, safety checks decide, it replays gently, it proves it worked and stops itself if it does not."
        },
        {
         "n": 4,
         "text": "Totals — rules on, replayed by rules, waiting for a person, stopped themselves."
        },
        {
         "n": 5,
         "text": "Namespace — Auto Replay rules apply to every AWS account and region you connected; this picks which one the page shows."
        },
        {
         "n": 6,
         "text": "Refresh rules — reads the rules again."
        },
        {
         "n": 7,
         "text": "Create your first rule — the same as Create rule, shown while there are none."
        }
       ]
      },
      {
       "image": "/help/aws/14-auto-replay-create.png",
       "alt": "6.1 Rules (14-auto-replay-create)",
       "keys": [
        {
         "n": 1,
         "text": "Based on — pick a failure ServiceHub has already seen. A rule can only be made from a seen failure."
        },
        {
         "n": 2,
         "text": "The guarantees: never in Production, same safety checks as you, and it stops itself if fewer than half stay fixed."
        },
        {
         "n": 3,
         "text": "Create and turn on — enabled once you choose a failure."
        },
        {
         "n": 4,
         "text": "Cancel — nothing is created."
        },
        {
         "n": 5,
         "text": "The page header — namespace, Refresh rules, Auto Generate Rules (proposes only) and the “How Auto Replay works” fold, as on the previous screenshot."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 7 — Settings, Help and Advanced",
   "steps": [
    {
     "title": "7.1 Settings",
     "text": "Connections, Notifications (Slack, Teams, any webhook — sent only when the Agent stops and needs a person), Preferences, Access & security (roles and the emergency stop) and Backup.",
     "shots": [
      {
       "image": "/help/aws/15-settings-connections.png",
       "alt": "7.1 Settings (15-settings-connections)",
       "keys": [
        {
         "n": 1,
         "text": "Sections — Connections, Notifications, Preferences, Access & security and Backup. Each jumps to that part of this window."
        },
        {
         "n": 2,
         "text": "Add a cloud — connect another cloud."
        },
        {
         "n": 3,
         "text": "Test — checks the connection now and shows the result. Reads only."
        },
        {
         "n": 4,
         "text": "Remove — forgets this connection and its stored credential. It does not delete anything in AWS."
        }
       ]
      },
      {
       "image": "/help/aws/15-settings-notifications.png",
       "alt": "7.1 Settings (15-settings-notifications)",
       "keys": [
        {
         "n": 1,
         "text": "In-app bell and pop-up — always on. It cannot be switched off, so it can never be switched off by mistake."
        },
        {
         "n": 2,
         "text": "Add webhook (Slack) — paste a Slack incoming-webhook URL to also get the message there."
        },
        {
         "n": 3,
         "text": "Add webhook (Microsoft Teams) — the same for a Teams channel."
        },
        {
         "n": 4,
         "text": "Add webhook (any other system) — JSON to a URL you choose. Private and internal addresses are refused."
        }
       ]
      },
      {
       "image": "/help/aws/15-settings-preferences.png",
       "alt": "7.1 Settings (15-settings-preferences)",
       "keys": [
        {
         "n": 1,
         "text": "Theme — Light today; Dark is marked soon."
        },
        {
         "n": 2,
         "text": "Times shown in — your browser’s time zone, or UTC. It changes how times are displayed, never the data."
        },
        {
         "n": 3,
         "text": "Open on — start in Simple every time (Simple), or where you last were (Last used). Kept in this browser only."
        }
       ]
      },
      {
       "image": "/help/aws/15-settings-access.png",
       "alt": "7.1 Settings (15-settings-access)",
       "keys": [
        {
         "n": 1,
         "text": "Who you are — shown from this browser session until roles are switched on. The credential key fingerprint shows what encrypts stored credentials."
        },
        {
         "n": 2,
         "text": "Roles — Viewer sees, Operator replays, Approver answers the Agent, Admin connects clouds. Giving the first role switches roles on."
        },
        {
         "n": 3,
         "text": "Who — the API key name or signed-in user the role is for."
        },
        {
         "n": 4,
         "text": "Kind, Role, Where and Grant — choose whether it is a key or a person, the role, whether it applies everywhere or to one namespace, then Grant. Granting the first role switches roles on for everyone."
        },
        {
         "n": 5,
         "text": "Emergency stop — type STOP, say why, and switch it on to halt every automatic action at once. Nothing already done is undone; switch it off to resume."
        }
       ]
      },
      {
       "image": "/help/aws/15-settings-backup.png",
       "alt": "7.1 Settings (15-settings-backup)",
       "keys": [
        {
         "n": 1,
         "text": "Take a backup now — saves a consistent copy of ServiceHub’s own database (not of your clouds)."
        }
       ]
      }
     ]
    },
    {
     "title": "7.2 Help, search and the bell",
     "text": "Help is a panel over whatever you are doing. Search (⌘K) jumps anywhere. The bell is the only place the Agent asks you something.",
     "shots": [
      {
       "image": "/help/aws/16-help.png",
       "alt": "7.2 Help, search and the bell (16-help)",
       "keys": [
        {
         "n": 1,
         "text": "Search — type what you are trying to do."
        },
        {
         "n": 2,
         "text": "An answer — click to open it in place; each links to the screen it is about."
        },
        {
         "n": 3,
         "text": "Setting up answers — connecting, alerts and who may replay."
        },
        {
         "n": 4,
         "text": "Keyboard shortcuts — only ones that work are listed."
        },
        {
         "n": 5,
         "text": "Step by step — one guide per cloud, each with every screen as a real screenshot and a numbered key for every button and link. Yours (AWS) is listed first. The same guides are the articles in docs/clouds."
        }
       ]
      },
      {
       "image": "/help/aws/16b-help-end.png",
       "alt": "7.2 Help, search and the bell (16b-help-end)",
       "keys": [
        {
         "n": 1,
         "text": "Answers and guides — click one to open it in place; the “Every screen” entries are one guide per cloud, each a real screenshot with a numbered key for every button and link."
        }
       ]
      },
      {
       "image": "/help/aws/18-search.png",
       "alt": "7.2 Help, search and the bell (18-search)",
       "keys": [
        {
         "n": 1,
         "text": "Search box — type part of a cloud, queue or page name. Enter opens the first result. Esc closes. Searching never changes anything."
        }
       ]
      },
      {
       "image": "/help/aws/18-bell.png",
       "alt": "7.2 Help, search and the bell (18-bell)",
       "keys": [
        {
         "n": 1,
         "text": "The bell — the only place the Agent asks you something. It lists what is waiting for you and clears when it is resolved, not when you look."
        },
        {
         "n": 2,
         "text": "See all waiting — opens the full list of what needs a person."
        }
       ]
      }
     ]
    },
    {
     "title": "7.3 The Advanced pages (read-only)",
     "text": "Advanced never changes anything. **Overview** summarises recovery, authority and agents, and says why AWS cannot verify; the **Recovery Ledger** is the tamper-evident record of every action; **Failure Signatures** groups failures and shows what each has earned; **Agents** lists what is acting and what is only watching.",
     "shots": [
      {
       "image": "/help/aws/17-advanced-overview.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-overview)",
       "keys": [
        {
         "n": 1,
         "text": "Scope — all clouds, or one."
        },
        {
         "n": 2,
         "text": "Window — the period the page counts over."
        },
        {
         "n": 3,
         "text": "Insights — patterns ServiceHub noticed across your failures."
        },
        {
         "n": 4,
         "text": "Recovery — how replays ended. “Recovered” means it did not come back, not that the business transaction completed."
        },
        {
         "n": 5,
         "text": "Authority — what each failure may do on its own, and what holds it there."
        },
        {
         "n": 6,
         "text": "Capability — what each cloud can prove."
        },
        {
         "n": 7,
         "text": "Being watched, All agents → and Recovery Ledger → — jump to the Agents page and the Recovery Ledger. They only open pages; nothing changes."
        },
        {
         "n": 8,
         "text": "Overview — the page you are on; the other three Advanced pages are in the bar at the top."
        },
        {
         "n": 9,
         "text": "Why → — explains why this cloud cannot yet prove a replayed message stayed fixed, and what would unlock it. It opens Help; nothing changes."
        }
       ]
      },
      {
       "image": "/help/aws/17-advanced-ledger.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-ledger)",
       "keys": [
        {
         "n": 1,
         "text": "Export evidence — downloads the ledger so it can be verified offline. It changes nothing."
        },
        {
         "n": 2,
         "text": "Outcome chips — Waiting, Watching, Recovered, Unverified, Returned, Failed, Unknown, Declined. Recovered and Unverified are never counted together."
        },
        {
         "n": 3,
         "text": "Filters — cloud, namespace, queue or topic, who did it, and search."
        },
        {
         "n": 4,
         "text": "Details — who took the action, what happened and its evidence. Each entry carries a fingerprint of the one before it."
        },
        {
         "n": 5,
         "text": "Filters and entries — namespace, queue or topic, who, and search narrow the list; each entry opens to show its evidence."
        },
        {
         "n": 6,
         "text": "What am I looking at? — a short reading guide for this page. Window — the period it counts over."
        },
        {
         "n": 7,
         "text": "Outcome chips with counts — click one to list only those entries; All shows everything again."
        },
        {
         "n": 8,
         "text": "Paging — how many rows per page, previous, the page number and next."
        },
        {
         "n": 9,
         "text": "The table headings — each has an ⓘ that explains that column in a sentence."
        }
       ]
      },
      {
       "image": "/help/aws/17-advanced-signatures.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-signatures)",
       "keys": [
        {
         "n": 1,
         "text": "Trace a message — follow one message across clouds by its ID."
        },
        {
         "n": 2,
         "text": "Growing — signatures whose recent days hold at least twice what earlier days did."
        },
        {
         "n": 3,
         "text": "Sort — most messages, or others."
        },
        {
         "n": 4,
         "text": "A signature — one way of failing: the same queue and the same kind of error, so many messages become one thing to reason about."
        },
        {
         "n": 5,
         "text": "Replays — how many of these were replayed and how many were verified to have held. On AWS none can be verified, and this says so."
        },
        {
         "n": 6,
         "text": "Filters — cloud, namespace, queue or topic, who, and search."
        },
        {
         "n": 7,
         "text": "Each signature row — opens to show the failures grouped under it and what each replay did."
        },
        {
         "n": 8,
         "text": "What am I looking at? — a short reading guide. Window — the period counted."
        },
        {
         "n": 9,
         "text": "Chips — Signatures, All, Replay helps, Replay doesn’t help. Click one to list only those."
        },
        {
         "n": 10,
         "text": "Paging — rows per page, previous, the page number and next."
        },
        {
         "n": 11,
         "text": "The table headings — Signature, Messages, Days and Replays, each with an ⓘ that explains it."
        }
       ]
      },
      {
       "image": "/help/aws/17c-advanced-signatures-end.png",
       "alt": "7.3 The Advanced pages (read-only) (17c-advanced-signatures-end)",
       "keys": [
        {
         "n": 1,
         "text": "Each signature row — opens to show the failures grouped under it and what each replay did."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next."
        },
        {
         "n": 3,
         "text": "The controls above the list — Signatures, Trace a message, the filters, search, sort, and the ⓘ About buttons on the headings — as on the previous screenshot."
        }
       ]
      },
      {
       "image": "/help/aws/17-advanced-agents.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-agents)",
       "keys": [
        {
         "n": 1,
         "text": "Acting agents — the only ones that can change anything, and only after the same safety checks you get."
        },
        {
         "n": 2,
         "text": "Watching agents — they only look and record."
        },
        {
         "n": 3,
         "text": "Pause — stops that agent acting. It is the one thing Advanced can do, because it only removes authority. Nothing it already did is undone."
        },
        {
         "n": 4,
         "text": "Learn more — a short explanation of how agents work."
        },
        {
         "n": 5,
         "text": "Health summary, agent rows and Open — the summary says whether every agent is running normally; a row opens that agent’s details; Open goes to the screen the agent works through."
        },
        {
         "n": 6,
         "text": "What am I looking at? — a short reading guide for this page."
        }
       ]
      },
      {
       "image": "/help/aws/17b-advanced-agents-more.png",
       "alt": "7.3 The Advanced pages (read-only) (17b-advanced-agents-more)",
       "keys": [
        {
         "n": 1,
         "text": "Watching agents — they only look and record; they cannot change anything."
        },
        {
         "n": 2,
         "text": "Each agent row opens to show what it may and may not do; Open goes to the screen it works through; Pause (acting agents only) stops it acting."
        },
        {
         "n": 3,
         "text": "Learn more — a short explanation of how agents work."
        }
       ]
      }
     ]
    }
   ]
  }
 ],
 "troubleshooting": [
  {
   "q": "Connect says the key is invalid or the signature does not match",
   "a": "Check the Access key ID and Secret access key were copied whole, with no spaces, and that the key is **Active** (IAM → the user → Security credentials). A secret cannot be shown again: if you lost it, create a new key."
  },
  {
   "q": "Connect works but finds 0 queues",
   "a": "Check the **region** — queues in another region are not seen — and that the policy includes `sqs:ListQueues` with Resource `*`."
  },
  {
   "q": "Dead letters stays empty after Look now",
   "a": "The dead-letter queue may really be empty, or the policy lacks `sqs:ReceiveMessage` on the dead-letter queue's ARN. Make sure both queue ARNs are in the policy's Resource list."
  },
  {
   "q": "Replay is unavailable or refused",
   "a": "The policy lacks `sqs:SendMessage` (to put the copy back) or `sqs:DeleteMessage` (to remove the dead-letter copy), or the main queue's ARN is missing from Resource."
  },
  {
   "q": "A looked-at message seems stuck for a while",
   "a": "The policy lacks `sqs:ChangeMessageVisibility`, so ServiceHub cannot hand a message back at once; SQS releases it after its visibility timeout (30 seconds by default). Add the action."
  },
  {
   "q": "The count is not exactly what the console shows",
   "a": "SQS counts are approximate and can lag a minute. Look now records up to 100 per queue, so the Dead letters tab can show fewer than the queue holds."
  },
  {
   "q": "Why does every replay say “Verification required”?",
   "a": "ServiceHub can prove a fix held only where the cloud can show the dead-letter queue stayed empty. AWS cannot, so ServiceHub records the replay honestly instead of calling it fixed."
  }
 ]
}
