// GENERATED by scripts/docs-shots/build_guides.py from the guide spec and the screenshots' keys.json — do not edit by hand.
import type { Guide } from './types'

export const azureGuide: Guide = {
 "cloud": "azure",
 "title": "Azure Service Bus",
 "sections": [
  {
   "part": "Part 1 — In the Azure portal",
   "steps": [
    {
     "title": "1.1 Open your Service Bus namespace",
     "text": "Sign in to the Azure portal, search for **Service Bus** and open your namespace. Note the **Host name** (it ends in `.servicebus.windows.net`) and that **Local Authentication** is *Enabled*. In the left menu, **Settings → Shared access policies** is where the next step happens.",
     "shots": [
      {
       "image": "/help/azure/portal-01-namespace-overview.png",
       "alt": "1.1 Open your Service Bus namespace (portal-01-namespace-overview)",
       "keys": [
        {
         "n": 1,
         "text": "Host name — the address of your namespace. Your connection string begins Endpoint=sb:// followed by this name."
        },
        {
         "n": 2,
         "text": "Pricing tier — Standard or Premium. Basic has no topics; queues work on every tier."
        },
        {
         "n": 3,
         "text": "Settings → Shared access policies — where you create and copy the connection string ServiceHub uses."
        },
        {
         "n": 4,
         "text": "Entities — your Queues and Topics live here."
        }
       ]
      }
     ]
    },
    {
     "title": "1.2 Shared access policies — and why not to reuse the default",
     "text": "Every namespace has `RootManageSharedAccessKey`, a default key shared by everything that touches the namespace. Give ServiceHub its **own** policy instead, so you can revoke it later without disturbing anything else.",
     "shots": [
      {
       "image": "/help/azure/portal-02-shared-access-policies.png",
       "alt": "1.2 Shared access policies — and why not to reuse the default (portal-02-shared-access-policies)",
       "keys": [
        {
         "n": 1,
         "text": "Add — creates a new policy. Make one just for ServiceHub, so you can revoke it without touching anything else."
        },
        {
         "n": 2,
         "text": "RootManageSharedAccessKey — the namespace's default key, shared by everything. Do not hand this one to ServiceHub."
        },
        {
         "n": 3,
         "text": "Any policy you already have for another tool — better not to share it. Give ServiceHub its own."
        }
       ]
      }
     ]
    },
    {
     "title": "1.3 Create a ServiceHub-only policy",
     "text": "Choose **Add**, name it (we use `servicehub-app`), tick **Manage** — Azure then ticks **Send** and **Listen** for you — and **Create**. Why Manage? Azure only lets a *Manage* policy **list** your queues and **count** their messages; with Listen and Send alone ServiceHub cannot even see which queues exist (Azure answers *401: Manage, EntityRead claims required*). ServiceHub uses *Send* only when you press Replay.",
     "shots": [
      {
       "image": "/help/azure/portal-03-add-policy.png",
       "alt": "1.3 Create a ServiceHub-only policy (portal-03-add-policy)",
       "keys": [
        {
         "n": 1,
         "text": "Policy name — for example servicehub-app, so you can recognise (and later revoke) it."
        },
        {
         "n": 2,
         "text": "Manage — required. Azure lets only Manage list your queues and count their messages; without it ServiceHub cannot see them."
        },
        {
         "n": 3,
         "text": "Send — used only when you press Replay, to put a copy of a dead letter back."
        },
        {
         "n": 4,
         "text": "Listen — used to read queues and dead-letter queues."
        }
       ]
      },
      {
       "image": "/help/azure/portal-03b-add-policy-filled.png",
       "alt": "1.3 Create a ServiceHub-only policy (portal-03b-add-policy-filled)",
       "keys": [
        {
         "n": 1,
         "text": "The name you chose."
        },
        {
         "n": 2,
         "text": "Manage, Send and Listen. Azure ticks Send and Listen for you when you tick Manage — Manage includes them."
        },
        {
         "n": 3,
         "text": "Create — saves the policy and generates its keys."
        }
       ]
      },
      {
       "image": "/help/azure/portal-04-policy-created.png",
       "alt": "1.3 Create a ServiceHub-only policy (portal-04-policy-created)",
       "keys": [
        {
         "n": 1,
         "text": "Your new policy appears in the list."
        },
        {
         "n": 2,
         "text": "Claims — Manage, Send, Listen."
        }
       ]
      }
     ]
    },
    {
     "title": "1.4 Copy the primary connection string",
     "text": "Open the new policy. The keys are hidden; click the copy icon beside **Primary connection string**. It begins `Endpoint=sb://…`. Treat it like a password: ServiceHub encrypts it on arrival and never shows it again, but anyone who has it can use it. The **Delete** button on this panel is how you revoke access later.",
     "shots": [
      {
       "image": "/help/azure/portal-05-connection-string.png",
       "alt": "1.4 Copy the primary connection string (portal-05-connection-string)",
       "keys": [
        {
         "n": 1,
         "text": "Claims — what this policy may do."
        },
        {
         "n": 2,
         "text": "Primary connection string — click the eye to reveal, then the copy icon. Paste this into ServiceHub. Treat it like a password."
        },
        {
         "n": 3,
         "text": "Copy to clipboard — copies the whole connection string."
        },
        {
         "n": 4,
         "text": "Delete — the way to revoke ServiceHub's access later."
        }
       ]
      }
     ]
    },
    {
     "title": "1.5 Check what is in your queues",
     "text": "Under **Entities → Queues** you can see each queue's *Active* and *Dead-letter* counts. Open a queue to see its **Max delivery count** (after that many failed tries Azure dead-letters the message) — ServiceHub's numbers should match these.",
     "shots": [
      {
       "image": "/help/azure/portal-06-queues.png",
       "alt": "1.5 Check what is in your queues (portal-06-queues)",
       "keys": [
        {
         "n": 1,
         "text": "Queue name — ServiceHub finds every queue in the namespace; you do not list them."
        },
        {
         "n": 2,
         "text": "Active messages — waiting to be processed."
        },
        {
         "n": 3,
         "text": "Dead-letter messages — failed too often and were set aside. These are what ServiceHub shows on its Dead letters tab."
        }
       ]
      },
      {
       "image": "/help/azure/portal-07-queue-overview.png",
       "alt": "1.5 Check what is in your queues (portal-07-queue-overview)",
       "keys": [
        {
         "n": 1,
         "text": "Max delivery count — how many tries before Azure dead-letters a message. Here 3."
        },
        {
         "n": 2,
         "text": "Message counts — Active and Dead-letter must match what ServiceHub shows."
        },
        {
         "n": 3,
         "text": "Dead lettering on expiry is off — messages here are dead-lettered by delivery count or by your app, which is all ServiceHub needs."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 2 — Connect Azure in ServiceHub",
   "steps": [
    {
     "title": "2.1 The welcome page",
     "text": "With no cloud connected, ServiceHub opens on a welcome page. Choose **Connect Azure**.",
     "shots": [
      {
       "image": "/help/azure/01-welcome.png",
       "alt": "2.1 The welcome page (01-welcome)",
       "keys": [
        {
         "n": 1,
         "text": "Connect Azure — opens the Add a cloud window on the Azure tab. It only asks for a connection string; nothing is read until you press Connect there."
        },
        {
         "n": 2,
         "text": "Add a cloud — the same window, from anywhere in the app. Use it later to connect AWS or Google Cloud as well."
        },
        {
         "n": 3,
         "text": "Simple | Advanced — Simple is where you act. Advanced is read-only pages (ledger, signatures, agents); it never changes anything."
        },
        {
         "n": 4,
         "text": "Help — opens the Help panel with task-shaped answers and the keyboard shortcuts."
        },
        {
         "n": 5,
         "text": "Connect AWS / Connect Google — the same Add a cloud window, on the AWS or Google Cloud tab. You do not need them for Azure."
        },
        {
         "n": 6,
         "text": "Try it with sample data — opens a demo with made-up data and no cloud connected, so you can look around first. Nothing in it is real and nothing is sent anywhere."
        }
       ]
      }
     ]
    },
    {
     "title": "2.2 Add a cloud",
     "text": "The window opens on the Azure tab. Open **Where do I get the Service Bus connection string?** for the same portal steps you just did.",
     "shots": [
      {
       "image": "/help/azure/02-add-cloud.png",
       "alt": "2.2 Add a cloud (02-add-cloud)",
       "keys": [
        {
         "n": 1,
         "text": "Cloud tabs — Azure Service Bus is selected. The AWS and Google tabs ask for different credentials."
        },
        {
         "n": 2,
         "text": "Where do I get the connection string? — expands the portal steps, with the permissions to give."
        },
        {
         "n": 3,
         "text": "Name — what you will see in ServiceHub. It is a label only; it does not change anything in Azure."
        },
        {
         "n": 4,
         "text": "Environment — Development, UAT or Production. Start with Development; Auto Replay never acts in Production."
        },
        {
         "n": 5,
         "text": "Connection string — paste the Primary connection string of a Shared access policy (Manage, Send, Listen). It is encrypted on this server and never shown again."
        },
        {
         "n": 6,
         "text": "Show value — reveals what you typed so you can check it. It cannot reveal a stored string."
        },
        {
         "n": 7,
         "text": "Cancel — closes the window; nothing is saved."
        },
        {
         "n": 8,
         "text": "Connect — tests the string, then saves it. It only reads queues; it never sends or deletes anything by itself."
        },
        {
         "n": 9,
         "text": "(?) — opens Help on this very screen. Every window has one."
        },
        {
         "n": 10,
         "text": "✕ — closes the window without saving (Esc does the same)."
        }
       ]
      },
      {
       "image": "/help/azure/02-add-cloud-help.png",
       "alt": "2.2 Add a cloud (02-add-cloud-help)",
       "keys": [
        {
         "n": 1,
         "text": "Settings → Shared access policies — in the Azure portal, on your Service Bus namespace."
        },
        {
         "n": 2,
         "text": "Tick Manage, Send and Listen. Azure only lets Manage list your queues and count messages; Send is used only when you replay."
        },
        {
         "n": 3,
         "text": "Copy the Primary connection string — it starts with Endpoint=sb://."
        },
        {
         "n": 4,
         "text": "The form underneath — the cloud tabs, Name, Environment, Connection string and Show value, exactly as in the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "2.3 Fill it in and connect",
     "text": "Give it a name, keep the environment as **Development** for your first connection, paste the connection string, and press **Connect**. ServiceHub tests the string, then saves it encrypted (AES-256-GCM).",
     "shots": [
      {
       "image": "/help/azure/03-add-cloud-filled.png",
       "alt": "2.3 Fill it in and connect (03-add-cloud-filled)",
       "keys": [
        {
         "n": 1,
         "text": "A name you will recognise."
        },
        {
         "n": 2,
         "text": "The connection string, hidden as you paste it."
        },
        {
         "n": 3,
         "text": "Connect — tests the connection, then saves it."
        },
        {
         "n": 4,
         "text": "The rest of the form — cloud tabs, Environment, Show value and Cancel, as described on the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "2.4 The result",
     "text": "You see exactly what ServiceHub can see: how many queues, topics and subscriptions, how many messages are dead-lettered right now, and whether this cloud can prove a replayed message stayed fixed (Azure can).",
     "shots": [
      {
       "image": "/help/azure/04-connected.png",
       "alt": "2.4 The result (04-connected)",
       "keys": [
        {
         "n": 1,
         "text": "The result: how many queues, topics and subscriptions ServiceHub found, how many messages are dead-lettered, and whether this cloud can prove a replay held."
        },
        {
         "n": 2,
         "text": "Open Home — closes the window and shows Home."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 3 — Learn the screens",
   "steps": [
    {
     "title": "3.1 Home",
     "text": "Home answers three questions: *what needs me*, *how is each cloud doing*, and *what is the Agent up to*. The Agent only acts on what it has earned (see Auto Replay below); until then it watches.",
     "shots": [
      {
       "image": "/help/azure/05-home.png",
       "alt": "3.1 Home (05-home)",
       "keys": [
        {
         "n": 1,
         "text": "Window — the period Home counts over (24 hours, 7 or 30 days). It changes what you see, never what happens."
        },
        {
         "n": 2,
         "text": "The Agent bar — what the Agent is doing, how many replays it verified, and how many it is still watching."
        },
        {
         "n": 3,
         "text": "Pause — stops the Agent acting until someone resumes it. It keeps watching and recording. Your own replays still work."
        },
        {
         "n": 4,
         "text": "What this cloud can do — ticks show what Azure lets ServiceHub do safely (count, watch, browse, prove a fix held, scheduled messages)."
        },
        {
         "n": 5,
         "text": "Dead letters — opens the list of messages that failed and were set aside."
        },
        {
         "n": 6,
         "text": "Active messages — browse what is waiting. On Azure, looking is not a delivery."
        },
        {
         "n": 7,
         "text": "Replayed — everything put back, by whom, and how it went."
        },
        {
         "n": 8,
         "text": "Auto Replay rules — opens the rules panel. A rule only acts once a failure has earned it."
        },
        {
         "n": 9,
         "text": "Got it — hides this explanation. It does not affect your data."
        },
        {
         "n": 10,
         "text": "See all dead letters in Azure — opens the Dead letters list for this cloud."
        },
        {
         "n": 11,
         "text": "Help for this page (the book beside the title) — opens Help on this very page, over it. Every page has one."
        },
        {
         "n": 12,
         "text": "Demo — a guided walk through the whole product with made-up data. No connection string is needed and nothing real is touched."
        }
       ]
      },
      {
       "image": "/help/azure/05c-home-middle.png",
       "alt": "3.1 Home (05c-home-middle)",
       "keys": [
        {
         "n": 1,
         "text": "Why messages failed — the reasons among the dead letters, biggest first, with how many each has. The window buttons (24 hours, 7 days, 30 days) set the period; Show as table swaps the chart for a table."
        },
        {
         "n": 2,
         "text": "How replays ended — what happened to the replays in this window."
        },
        {
         "n": 3,
         "text": "7, 14, 30 days and Show as table — change the period Home counts over, or show the numbers as a table. They never change what happens."
        },
        {
         "n": 4,
         "text": "Latest dead letters and Recent activity — shown in full on the next screenshot."
        },
        {
         "n": 5,
         "text": "Window buttons (7, 14, 30 days) and Open → — change the period, or open that item’s page. They never change what happens."
        }
       ]
      },
      {
       "image": "/help/azure/05d-home-end.png",
       "alt": "3.1 Home (05d-home-end)",
       "keys": [
        {
         "n": 1,
         "text": "The latest dead letters, each with Details → — the same message view as on the Dead letters tab. “See all →” opens the full list."
        },
        {
         "n": 2,
         "text": "Recent activity — what ServiceHub and people did, newest first. Each line opens to show its detail; nothing here changes anything."
        },
        {
         "n": 3,
         "text": "Open → — opens that item’s page. It only navigates."
        },
        {
         "n": 4,
         "text": "Connected — a note that a namespace was connected, with when and by whom. Opens to show the detail."
        },
        {
         "n": 5,
         "text": "Window buttons, Show as table, and the reasons — each reason opens the dead letters with that reason. They only change what is shown."
        }
       ]
      }
     ]
    },
    {
     "title": "3.2 The bar and the sidebar",
     "text": "These are the same on every page.",
     "shots": [
      {
       "image": "/help/azure/05b-navigation.png",
       "alt": "3.2 The bar and the sidebar (05b-navigation)",
       "keys": [
        {
         "n": 1,
         "text": "Back — returns to the previous place in the app."
        },
        {
         "n": 2,
         "text": "Forward — goes to the place you came back from."
        },
        {
         "n": 3,
         "text": "Search (⌘K) — jump to a cloud, queue or page. Searching never changes anything."
        },
        {
         "n": 4,
         "text": "The bell — the only place the Agent asks you something. A number appears when it needs you."
        },
        {
         "n": 5,
         "text": "Simple — the two pages where you do the work."
        },
        {
         "n": 6,
         "text": "Advanced — four read-only pages."
        },
        {
         "n": 7,
         "text": "You — who ServiceHub records actions as, with your role."
        },
        {
         "n": 8,
         "text": "Dead letters — messages that failed, with the reason and a Replay button."
        },
        {
         "n": 9,
         "text": "Active messages — what is waiting now."
        },
        {
         "n": 10,
         "text": "Replayed — what was put back and whether it stayed fixed."
        },
        {
         "n": 11,
         "text": "Auto Replay — rules for retries ServiceHub may do on its own."
        },
        {
         "n": 12,
         "text": "Your cloud — pick it to see only that cloud. The dot shows the connection is healthy."
        },
        {
         "n": 13,
         "text": "Connections — your connected clouds, to test or remove."
        },
        {
         "n": 14,
         "text": "Add a cloud — connect another cloud."
        },
        {
         "n": 15,
         "text": "Settings — connections, notifications, preferences, access and backup."
        },
        {
         "n": 16,
         "text": "Help — answers and shortcuts."
        },
        {
         "n": 17,
         "text": "Home — the overview: what needs attention, what the Agent is doing, and how replays ended."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 4 — Work with dead letters",
   "steps": [
    {
     "title": "4.1 The Dead letters tab",
     "text": "A **dead letter** is a message your consumer failed to process several times, so Azure set it aside in the queue's dead-letter queue. ServiceHub groups them by the reason your sender recorded.",
     "shots": [
      {
       "image": "/help/azure/06-dead-letters.png",
       "alt": "4.1 The Dead letters tab (06-dead-letters)",
       "keys": [
        {
         "n": 1,
         "text": "Namespace picker — all of Azure, or one namespace."
        },
        {
         "n": 2,
         "text": "Why they failed — the biggest reasons, counted. The reason comes from what your sender wrote when it dead-lettered the message."
        },
        {
         "n": 3,
         "text": "Dead letters tab — messages set aside. The number is how many are stuck now."
        },
        {
         "n": 4,
         "text": "Active tab — what is waiting in the queue."
        },
        {
         "n": 5,
         "text": "Replayed tab — what has been put back."
        },
        {
         "n": 6,
         "text": "Reason chips — click one to show only that reason."
        },
        {
         "n": 7,
         "text": "Help for this page — opens Help on this page’s step of the guide. The (?) beside it only re-shows the short explanation."
        }
       ]
      }
     ]
    },
    {
     "title": "4.2 Filters, selection and the table",
     "text": "Narrow the list, tick the messages you want, and use **Details** or **Replay** on a row.",
     "shots": [
      {
       "image": "/help/azure/07-filters-and-table.png",
       "alt": "4.2 Filters, selection and the table (07-filters-and-table)",
       "keys": [
        {
         "n": 1,
         "text": "Showing — Stuck now, or messages that have since left the queue."
        },
        {
         "n": 2,
         "text": "Time window — only messages set aside in this period."
        },
        {
         "n": 3,
         "text": "Search — by message ID, queue, reason or error text."
        },
        {
         "n": 4,
         "text": "Replay All Messages — opens a preview of every message still stuck in the cloud and namespace you are viewing. It ignores the filters, time window and search here. Nothing is sent until you confirm the preview."
        },
        {
         "n": 5,
         "text": "Refresh — reads the queue again. On Azure this is free. The ⓘ beside it says when it was last read."
        },
        {
         "n": 6,
         "text": "Selection — tick rows to act on several; this line shows how many."
        },
        {
         "n": 7,
         "text": "Replay selected — opens the same preview for just the ticked messages."
        },
        {
         "n": 8,
         "text": "Details — opens the message: why it failed, its body, properties and delivery history."
        },
        {
         "n": 9,
         "text": "Replay — opens the proposal for this one message. It does not send anything yet."
        },
        {
         "n": 10,
         "text": "The table — a tick on every row (the one in the heading ticks the whole page), Details and Replay on every row, and an ⓘ About button on each column heading that explains that column in a sentence. “View details” in the heading chooses which columns show."
        },
        {
         "n": 11,
         "text": "Reason chips — each shows a reason and how many messages have it. Click one to show only those; click it again to show all."
        },
        {
         "n": 12,
         "text": "All queues & topics — limit the list to one queue or topic."
        },
        {
         "n": 13,
         "text": "The selection bar — the tick selects every row on this page; View details chooses which columns show; Replay selected stays dimmed until something is ticked."
        }
       ]
      },
      {
       "image": "/help/azure/07c-table-end.png",
       "alt": "4.2 Filters, selection and the table (07c-table-end)",
       "keys": [
        {
         "n": 1,
         "text": "The foot of the table — the same ticks, Details and Replay on every row."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next."
        }
       ]
      },
      {
       "image": "/help/azure/07b-selection.png",
       "alt": "4.2 Filters, selection and the table (07b-selection)",
       "keys": [
        {
         "n": 1,
         "text": "Row tick — choose which messages to act on. The header tick chooses every row on the page."
        },
        {
         "n": 2,
         "text": "Selection count — how many messages are ticked."
        },
        {
         "n": 3,
         "text": "Clear — unticks everything. Nothing else changes."
        },
        {
         "n": 4,
         "text": "Replay selected — opens the bulk preview for just these messages. Nothing is sent yet."
        },
        {
         "n": 5,
         "text": "The filter row — reason chips, Showing, Time window, queue, search, Replay All Messages and Refresh, each explained on the previous screenshot."
        },
        {
         "n": 6,
         "text": "The table — the ticks, Details and Replay on every row, and the whole-page tick in the heading."
        },
        {
         "n": 7,
         "text": "The selection bar — the whole-page tick and View details (which columns show)."
        }
       ]
      }
     ]
    },
    {
     "title": "4.3 Open a message",
     "text": "**Details** opens the message: the reason, a plain-words reading of why it failed (marked *Suggestion* because it is a reading, not something Azure reported), and the body with the bad field marked. The tabs show the body, properties, headers and delivery history.",
     "shots": [
      {
       "image": "/help/azure/08-message-details.png",
       "alt": "4.3 Open a message (08-message-details)",
       "keys": [
        {
         "n": 1,
         "text": "Expand — widens the panel for long messages."
        },
        {
         "n": 2,
         "text": "Overview — reason, why it failed, the body with the bad field marked."
        },
        {
         "n": 3,
         "text": "Delivery — the delivery history Azure recorded."
        },
        {
         "n": 4,
         "text": "Why it failed — a plain-words reading of the recorded reason. Marked Suggestion: it is a reading, not something Azure reported."
        },
        {
         "n": 5,
         "text": "Formatted / Raw — switch the body view."
        },
        {
         "n": 6,
         "text": "Replay this message — opens the proposal. Nothing is sent from here."
        },
        {
         "n": 7,
         "text": "Body, Properties and Headers — the other tabs; each is shown below."
        },
        {
         "n": 8,
         "text": "Formatted and Copy body — pretty-print the body, or copy it to your clipboard. The copy stays in your browser."
        },
        {
         "n": 9,
         "text": "Copy message ID — copies the ID so you can search for it elsewhere."
        }
       ]
      },
      {
       "image": "/help/azure/08-message-details-body.png",
       "alt": "4.3 Open a message (08-message-details-body)",
       "keys": [
        {
         "n": 1,
         "text": "The message body exactly as it was sent."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        },
        {
         "n": 3,
         "text": "Formatted / Raw switch the view; Copy body copies it to your clipboard."
        }
       ]
      },
      {
       "image": "/help/azure/08-message-details-properties.png",
       "alt": "4.3 Open a message (08-message-details-properties)",
       "keys": [
        {
         "n": 1,
         "text": "Application properties and system properties (message ID, content type, subject)."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      },
      {
       "image": "/help/azure/08-message-details-headers.png",
       "alt": "4.3 Open a message (08-message-details-headers)",
       "keys": [
        {
         "n": 1,
         "text": "Broker headers: enqueued time, lock and sequence information."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      },
      {
       "image": "/help/azure/08-message-details-delivery.png",
       "alt": "4.3 Open a message (08-message-details-delivery)",
       "keys": [
        {
         "n": 1,
         "text": "How many times Azure tried, and when it set the message aside."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      }
     ]
    },
    {
     "title": "4.4 Replay one message — you see the proposal first",
     "text": "**Replay** never sends straight away. It shows what will happen, every safety check, and what happens afterwards. Only the blue button sends.",
     "shots": [
      {
       "image": "/help/azure/09-replay-proposal.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal)",
       "keys": [
        {
         "n": 1,
         "text": "The message — what is about to be replayed: ID, where it is stuck, when and why it was set aside, and its body."
        },
        {
         "n": 2,
         "text": "Replay 1 message — sends it back. It is only sent when you press this."
        },
        {
         "n": 3,
         "text": "What will happen, Safety checks, After it runs — fold open or closed; the next screenshot shows them open."
        },
        {
         "n": 4,
         "text": "Cancel — closes without sending."
        }
       ]
      },
      {
       "image": "/help/azure/09-replay-proposal-checks.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal-checks)",
       "keys": [
        {
         "n": 1,
         "text": "What will happen — where it goes and what happens to the dead-letter copy (it is removed once Azure accepts the new one)."
        },
        {
         "n": 2,
         "text": "Safety checks — every check that must pass; a failing one blocks the replay and says why."
        },
        {
         "n": 3,
         "text": "After it runs — ServiceHub records it and watches for 24 hours; if it comes back, nothing retries it."
        },
        {
         "n": 4,
         "text": "Cancel — closes without sending."
        },
        {
         "n": 5,
         "text": "The folding headings and the Replay button repeated at the end of the window."
        }
       ]
      }
     ]
    },
    {
     "title": "4.5 Replay several at once",
     "text": "Tick messages (or use **Replay All Messages**) to get a preview: how many will be replayed, which are held back by a safety check, grouped by how they failed and where each goes. They are sent one at a time and each is re-checked.",
     "shots": [
      {
       "image": "/help/azure/13-bulk-replay.png",
       "alt": "4.5 Replay several at once (13-bulk-replay)",
       "keys": [
        {
         "n": 1,
         "text": "Preview — nothing has run yet. Step 1 of Preview → Run → Watch."
        },
        {
         "n": 2,
         "text": "Held back — messages that fail a safety check stay in dead letters; they are never forced."
        },
        {
         "n": 3,
         "text": "Grouped by how they failed — so you can see whether you are fixing one problem or several."
        },
        {
         "n": 4,
         "text": "Where each one goes — the queue each message will be sent back to."
        },
        {
         "n": 5,
         "text": "Replay N messages — sends them one at a time, re-checking each. You can stop partway."
        },
        {
         "n": 6,
         "text": "Cancel — nothing is sent."
        },
        {
         "n": 7,
         "text": "Page controls — move through the list when more messages are chosen than fit on one page."
        },
        {
         "n": 8,
         "text": "How it will run — folds open to show the pace and the automatic stop (five failures in a row)."
        },
        {
         "n": 9,
         "text": "After they are sent back — what ServiceHub does next: it records each replay and watches for 24 hours."
        }
       ]
      },
      {
       "image": "/help/azure/13b-bulk-replay-end.png",
       "alt": "4.5 Replay several at once (13b-bulk-replay-end)",
       "keys": [
        {
         "n": 1,
         "text": "How it will run — the pace (a few messages a second, gentle on your consumer) and the automatic stop: five failures in a row."
        },
        {
         "n": 2,
         "text": "After they are sent back — what ServiceHub does next: it records each replay and watches for 24 hours."
        },
        {
         "n": 3,
         "text": "No purge on Azure — this cloud cannot delete one message on its own, so ServiceHub does not offer “Purge instead…” here (AWS and Google Cloud do)."
        },
        {
         "n": 4,
         "text": "Replay N messages — sends them one at a time, re-checking each. You can stop partway."
        },
        {
         "n": 5,
         "text": "Cancel — nothing is sent."
        },
        {
         "n": 6,
         "text": "Page controls — move through the list when more messages are chosen than fit on one page."
        },
        {
         "n": 7,
         "text": "Where each one goes — folds open to list the queue each message will be sent back to, grouped by why it failed."
        }
       ]
      }
     ]
    },
    {
     "title": "4.6 The result",
     "text": "ServiceHub says plainly what happened, records it under Replayed, and starts a 24-hour watch for it coming back.",
     "shots": [
      {
       "image": "/help/azure/10-replay-result.png",
       "alt": "4.6 The result (10-replay-result)",
       "keys": [
        {
         "n": 1,
         "text": "The result, in plain words: it was sent back, and ServiceHub will watch for it coming back."
        },
        {
         "n": 2,
         "text": "It is recorded, with who did it, and shows under Replayed (and in Advanced → Recovery Ledger)."
        },
        {
         "n": 3,
         "text": "Done — closes the window."
        },
        {
         "n": 4,
         "text": "Active messages / Replayed — jump to where you can watch this message."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 5 — Afterwards",
   "steps": [
    {
     "title": "5.1 Replayed",
     "text": "Every replay, who did it, and how it ended. On Azure ServiceHub can **prove** whether a replayed message stayed out of the dead-letter queue, so the result moves from *Watching* to *Stayed fixed* or *Came back*.",
     "shots": [
      {
       "image": "/help/azure/11-replayed.png",
       "alt": "5.1 Replayed (11-replayed)",
       "keys": [
        {
         "n": 1,
         "text": "Messages replayed — how many were put back in the window."
        },
        {
         "n": 2,
         "text": "Being watched — replays still inside their watch window. Azure can prove whether each stayed fixed."
        },
        {
         "n": 3,
         "text": "Came back — messages that failed the same way again. Nothing retries them on its own."
        },
        {
         "n": 4,
         "text": "Result filter — stayed fixed, being watched, came back."
        },
        {
         "n": 5,
         "text": "Download — saves this list as a file. It does not change anything."
        },
        {
         "n": 6,
         "text": "Details — the full record of this replay."
        },
        {
         "n": 7,
         "text": "Filters — namespace, queue or topic, result, time window and search; Refresh reads the list again. They change what is listed, never what happened."
        },
        {
         "n": 8,
         "text": "The table — a tick per replay (the heading tick ticks the page) and Details on each row."
        },
        {
         "n": 9,
         "text": "What am I looking at? — a short reading guide. Auto Replay rules — opens the rules page. All and Last 24 hours — the result and time filters."
        },
        {
         "n": 10,
         "text": "The three tabs — Dead letters, Active and Replayed. They switch the list below without leaving the page."
        },
        {
         "n": 11,
         "text": "Paging — rows per page, previous, the page numbers and next."
        }
       ]
      },
      {
       "image": "/help/azure/11b-replayed-end.png",
       "alt": "5.1 Replayed (11b-replayed-end)",
       "keys": [
        {
         "n": 1,
         "text": "The replays, newest first — each with a tick and Details."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next."
        },
        {
         "n": 3,
         "text": "The three tabs, the Auto Replay rules button, and the table headings with their ⓘ About buttons — as on the previous screenshot."
        },
        {
         "n": 4,
         "text": "Filters — result, queue or topic, time window and search; Refresh re-reads the list and Download as CSV saves it as a file. They change what is listed, never what happened."
        }
       ]
      }
     ]
    },
    {
     "title": "5.2 Active messages",
     "text": "What is waiting right now. Looking does not touch anything on Azure — a peek is not a delivery. **Send a message** is the one control here that changes a queue.",
     "shots": [
      {
       "image": "/help/azure/12-active.png",
       "alt": "5.2 Active messages (12-active)",
       "keys": [
        {
         "n": 1,
         "text": "Send a message — puts a test message on the queue. This does change the queue, so use a dev queue."
        },
        {
         "n": 2,
         "text": "Counts — waiting, oldest, delivered before, dead-lettered."
        },
        {
         "n": 3,
         "text": "Filters — queue or topic, message state, time window and search."
        },
        {
         "n": 4,
         "text": "Follow live — shows new messages as they arrive. On Azure, looking does not count as a delivery."
        },
        {
         "n": 5,
         "text": "Auto-refresh — re-reads the queue every 15 seconds."
        },
        {
         "n": 6,
         "text": "Scheduled — messages set to arrive later."
        },
        {
         "n": 7,
         "text": "Peek message — opens one message to read it. Peeking does not remove or lock it."
        },
        {
         "n": 8,
         "text": "Filters and tools — namespace, queue, time window, search, how often the list refreshes, Refresh now, and Download body (saves the shown messages’ bodies as a file; changes nothing)."
        },
        {
         "n": 9,
         "text": "Dead-lettered — jumps to the dead letters in this queue."
        },
        {
         "n": 10,
         "text": "The table — a tick per message (the heading tick ticks the page) and Details on each row."
        },
        {
         "n": 11,
         "text": "What am I looking at? — a short reading guide. The queue and time-window pickers narrow what is listed."
        },
        {
         "n": 12,
         "text": "The three tabs — Dead letters, Active and Replayed. They switch the list below without leaving the page."
        }
       ]
      },
      {
       "image": "/help/azure/12b-active-end.png",
       "alt": "5.2 Active messages (12b-active-end)",
       "keys": [
        {
         "n": 1,
         "text": "A message row — a tick to choose it, and Details to open it (body, properties, delivery). Looking at an Azure message is not a delivery."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next."
        },
        {
         "n": 3,
         "text": "The controls above the table — the same filters, search, auto-refresh, Refresh, Scheduled, and the ⓘ About buttons on the column headings, as on the previous screenshot."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 6 — Auto Replay",
   "steps": [
    {
     "title": "6.1 Rules",
     "text": "A rule names a failure ServiceHub has already seen and how carefully to retry it. It never runs in Production namespaces, goes through the same safety checks as you, and **stops itself** if fewer than half of its replays stay fixed. A rule only acts once that failure has 10 verified fixes at 95% or better.",
     "shots": [
      {
       "image": "/help/azure/14-auto-replay.png",
       "alt": "6.1 Rules (14-auto-replay)",
       "keys": [
        {
         "n": 1,
         "text": "Auto Generate Rules — proposes rules from failures already seen. It only proposes; you decide what to turn on."
        },
        {
         "n": 2,
         "text": "Create rule — start a rule from a failure you have already seen."
        },
        {
         "n": 3,
         "text": "How it works — you name a failure, safety checks decide, it replays gently, it proves it worked and stops itself if it does not."
        },
        {
         "n": 4,
         "text": "Totals — rules on, replayed by rules, waiting for a person, stopped themselves."
        },
        {
         "n": 5,
         "text": "Namespace — Auto Replay rules apply to every Azure namespace; this picks which one the page shows."
        },
        {
         "n": 6,
         "text": "Refresh rules — reads the rules again."
        },
        {
         "n": 7,
         "text": "Create your first rule — the same as Create rule, shown while there are none."
        }
       ]
      },
      {
       "image": "/help/azure/14-auto-replay-create.png",
       "alt": "6.1 Rules (14-auto-replay-create)",
       "keys": [
        {
         "n": 1,
         "text": "Based on — pick a failure ServiceHub has already seen. A rule can only be made from a seen failure."
        },
        {
         "n": 2,
         "text": "The guarantees: never in Production, same safety checks as you, and it stops itself if fewer than half stay fixed."
        },
        {
         "n": 3,
         "text": "Create and turn on — enabled once you choose a failure."
        },
        {
         "n": 4,
         "text": "Cancel — nothing is created."
        },
        {
         "n": 5,
         "text": "The page header — namespace, Refresh rules, Auto Generate Rules (proposes only) and the “How Auto Replay works” fold, as on the previous screenshot."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 7 — Settings, Help and Advanced",
   "steps": [
    {
     "title": "7.1 Settings",
     "text": "Connections, Notifications (Slack, Teams, any webhook — sent only when the Agent stops and needs a person), Preferences, Access & security (roles and the emergency stop) and Backup.",
     "shots": [
      {
       "image": "/help/azure/15-settings-connections.png",
       "alt": "7.1 Settings (15-settings-connections)",
       "keys": [
        {
         "n": 1,
         "text": "Sections — Connections, Notifications, Preferences, Access & security and Backup. Each jumps to that part of this window."
        },
        {
         "n": 2,
         "text": "Add a cloud — connect another cloud."
        },
        {
         "n": 3,
         "text": "Test — checks the connection now and shows the result. Reads only."
        },
        {
         "n": 4,
         "text": "Remove — forgets this connection and its stored credential. It does not delete anything in Azure."
        }
       ]
      },
      {
       "image": "/help/azure/15-settings-notifications.png",
       "alt": "7.1 Settings (15-settings-notifications)",
       "keys": [
        {
         "n": 1,
         "text": "In-app bell and pop-up — always on. It cannot be switched off, so it can never be switched off by mistake."
        },
        {
         "n": 2,
         "text": "Add webhook (Slack) — paste a Slack incoming-webhook URL to also get the message there."
        },
        {
         "n": 3,
         "text": "Add webhook (Microsoft Teams) — the same for a Teams channel."
        },
        {
         "n": 4,
         "text": "Add webhook (any other system) — JSON to a URL you choose. Private and internal addresses are refused."
        }
       ]
      },
      {
       "image": "/help/azure/15-settings-preferences.png",
       "alt": "7.1 Settings (15-settings-preferences)",
       "keys": [
        {
         "n": 1,
         "text": "Theme — Light today; Dark is marked soon."
        },
        {
         "n": 2,
         "text": "Times shown in — your browser’s time zone, or UTC. It changes how times are displayed, never the data."
        },
        {
         "n": 3,
         "text": "Open on — start in Simple every time (Simple), or where you last were (Last used). Kept in this browser only."
        },
        {
         "n": 4,
         "text": "Your tracing tool — optional. Paste a link with {traceId} in it, and ServiceHub shows a link from each message to that trace in your own tool. It is kept in this browser only."
        }
       ]
      },
      {
       "image": "/help/azure/15-settings-access.png",
       "alt": "7.1 Settings (15-settings-access)",
       "keys": [
        {
         "n": 1,
         "text": "Who you are — shown from this browser session until roles are switched on. The credential key fingerprint shows what encrypts stored credentials."
        },
        {
         "n": 2,
         "text": "Roles — Viewer sees, Operator replays, Approver answers the Agent, Admin connects clouds. Giving the first role switches roles on."
        },
        {
         "n": 3,
         "text": "Who — the API key name or signed-in user the role is for."
        },
        {
         "n": 4,
         "text": "Kind, Role, Where and Grant — choose whether it is a key or a person, the role, whether it applies everywhere or to one namespace, then Grant. Granting the first role switches roles on for everyone."
        },
        {
         "n": 5,
         "text": "Emergency stop — type STOP, say why, and switch it on to halt every automatic action at once. Nothing already done is undone; switch it off to resume."
        }
       ]
      },
      {
       "image": "/help/azure/15-settings-backup.png",
       "alt": "7.1 Settings (15-settings-backup)",
       "keys": [
        {
         "n": 1,
         "text": "Take a backup now — saves a consistent copy of ServiceHub’s own database (not of your clouds)."
        }
       ]
      }
     ]
    },
    {
     "title": "7.2 Help, search and the bell",
     "text": "Help is a panel over whatever you are doing. Search (⌘K) jumps anywhere. The bell is the only place the Agent asks you something.",
     "shots": [
      {
       "image": "/help/azure/16-help.png",
       "alt": "7.2 Help, search and the bell (16-help)",
       "keys": [
        {
         "n": 1,
         "text": "Search — type what you are trying to do."
        },
        {
         "n": 2,
         "text": "An answer — click to open it in place; each links to the screen it is about."
        },
        {
         "n": 3,
         "text": "Setting up answers — connecting, alerts and who may replay."
        },
        {
         "n": 4,
         "text": "Keyboard shortcuts — only ones that work are listed."
        },
        {
         "n": 5,
         "text": "Step by step — one guide per cloud, each with every screen as a real screenshot and a numbered key for every button and link. Yours (Azure) is listed first. The same guides are the articles in docs/clouds."
        }
       ]
      },
      {
       "image": "/help/azure/16b-help-end.png",
       "alt": "7.2 Help, search and the bell (16b-help-end)",
       "keys": [
        {
         "n": 1,
         "text": "Step by step — one guide per cloud, each with every screen as a real screenshot and a numbered key for every button and link."
        },
        {
         "n": 2,
         "text": "Answers — click one to open it in place; each links to the screen it is about."
        }
       ]
      },
      {
       "image": "/help/azure/18-search.png",
       "alt": "7.2 Help, search and the bell (18-search)",
       "keys": [
        {
         "n": 1,
         "text": "Search box — type part of a cloud, queue or page name. Enter opens the first result. Esc closes. Searching never changes anything."
        }
       ]
      },
      {
       "image": "/help/azure/18-bell.png",
       "alt": "7.2 Help, search and the bell (18-bell)",
       "keys": [
        {
         "n": 1,
         "text": "The bell — the only place the Agent asks you something. It lists what is waiting for you and clears when it is resolved, not when you look."
        },
        {
         "n": 2,
         "text": "See all waiting — opens the full list of what needs a person."
        }
       ]
      }
     ]
    },
    {
     "title": "7.3 The Advanced pages (read-only)",
     "text": "Advanced never changes anything. **Overview** summarises recovery, authority and agents; the **Recovery Ledger** is the tamper-evident record of every action; **Failure Signatures** groups failures — by cloud, queue, reason and, where the cloud records one, the shape of the error message — and shows what each has earned (if some of a group’s latest replays did not hold, ServiceHub stops replaying it on its own until newer ones do); **Agents** lists what is acting and what is only watching.",
     "shots": [
      {
       "image": "/help/azure/17-advanced-overview.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-overview)",
       "keys": [
        {
         "n": 1,
         "text": "Scope — all clouds, or one."
        },
        {
         "n": 2,
         "text": "Window — the period the page counts over."
        },
        {
         "n": 3,
         "text": "Insights — patterns ServiceHub noticed across your failures."
        },
        {
         "n": 4,
         "text": "Recovery — how replays ended. “Recovered” means it did not come back, not that the business transaction completed."
        },
        {
         "n": 5,
         "text": "Authority — what each failure may do on its own, and what holds it there."
        },
        {
         "n": 6,
         "text": "Capability — what each cloud can prove."
        },
        {
         "n": 7,
         "text": "Being watched, All agents → and Recovery Ledger → — jump to the Agents page and the Recovery Ledger. They only open pages; nothing changes."
        },
        {
         "n": 8,
         "text": "Overview — the page you are on; the other three Advanced pages are in the bar at the top."
        }
       ]
      },
      {
       "image": "/help/azure/17-advanced-ledger.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-ledger)",
       "keys": [
        {
         "n": 1,
         "text": "Export evidence — downloads the ledger so it can be verified offline. It changes nothing."
        },
        {
         "n": 2,
         "text": "Outcome chips — Waiting, Watching, Recovered, Unverified, Returned, Failed, Unknown, Declined. Recovered and Unverified are never counted together."
        },
        {
         "n": 3,
         "text": "Filters — cloud, namespace, queue or topic, who did it, and search."
        },
        {
         "n": 4,
         "text": "Details — who took the action, what happened and its evidence. Each entry carries a fingerprint of the one before it."
        },
        {
         "n": 5,
         "text": "Filters and entries — namespace, queue or topic, who, and search narrow the list; each entry opens to show its evidence."
        },
        {
         "n": 6,
         "text": "What am I looking at? — a short reading guide for this page. Window — the period it counts over."
        },
        {
         "n": 7,
         "text": "Outcome chips with counts — click one to list only those entries; All shows everything again."
        },
        {
         "n": 8,
         "text": "Paging — how many rows per page, previous, the page number and next."
        },
        {
         "n": 9,
         "text": "About buttons (ⓘ) on the column headings — each explains that column in a sentence. They change nothing."
        }
       ]
      },
      {
       "image": "/help/azure/17-advanced-signatures.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-signatures)",
       "keys": [
        {
         "n": 1,
         "text": "Trace a message — follow one message across clouds by its ID."
        },
        {
         "n": 2,
         "text": "Growing — signatures whose recent days hold at least twice what earlier days did."
        },
        {
         "n": 3,
         "text": "Sort — most messages, or others."
        },
        {
         "n": 4,
         "text": "A signature — one way of failing: the same queue and the same kind of error, so many messages become one thing to reason about."
        },
        {
         "n": 5,
         "text": "Replays — how many of these were replayed and how many were verified to have held."
        },
        {
         "n": 6,
         "text": "Filters — cloud, namespace, queue or topic, who, and search."
        },
        {
         "n": 7,
         "text": "Each signature row — opens to show the failures grouped under it and what each replay did."
        },
        {
         "n": 8,
         "text": "What am I looking at? — a short reading guide. Window — the period counted."
        },
        {
         "n": 9,
         "text": "Chips — Signatures, All, Replay helps, Replay doesn’t help. Click one to list only those."
        },
        {
         "n": 10,
         "text": "Paging — rows per page, previous, the page number and next."
        },
        {
         "n": 11,
         "text": "About buttons (ⓘ) on the column headings — each explains that column in a sentence. They change nothing."
        }
       ]
      },
      {
       "image": "/help/azure/17d-advanced-signatures-end.png",
       "alt": "7.3 The Advanced pages (read-only) (17d-advanced-signatures-end)",
       "keys": [
        {
         "n": 1,
         "text": "Paging — rows per page, previous, the page numbers and next."
        }
       ]
      },
      {
       "image": "/help/azure/17-advanced-agents.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-agents)",
       "keys": [
        {
         "n": 1,
         "text": "Acting agents — the only ones that can change anything, and only after the same safety checks you get."
        },
        {
         "n": 2,
         "text": "Watching agents — they only look and record."
        },
        {
         "n": 3,
         "text": "Pause — stops that agent acting. It is the one thing Advanced can do, because it only removes authority. Nothing it already did is undone."
        },
        {
         "n": 4,
         "text": "Learn more — a short explanation of how agents work."
        },
        {
         "n": 5,
         "text": "Health summary, agent rows and Open — the summary says whether every agent is running normally; a row opens that agent’s details; Open goes to the screen the agent works through."
        },
        {
         "n": 6,
         "text": "What am I looking at? — a short reading guide for this page."
        }
       ]
      },
      {
       "image": "/help/azure/17a-advanced-agents-middle.png",
       "alt": "7.3 The Advanced pages (read-only) (17a-advanced-agents-middle)",
       "keys": [
        {
         "n": 1,
         "text": "Agent rows — click a row to see what that agent may and may not do; Open goes to the screen it works through; Pause (acting agents only) stops it acting."
        },
        {
         "n": 2,
         "text": "More agent rows — the acting agents (Bulk Replay, Auto Replay) and the rest; each opens to show what it may do."
        }
       ]
      },
      {
       "image": "/help/azure/17c-advanced-agents-rows.png",
       "alt": "7.3 The Advanced pages (read-only) (17c-advanced-agents-rows)",
       "keys": [
        {
         "n": 1,
         "text": "Agent rows — click a row to see what that agent may and may not do; Open goes to the screen it works through; Pause (acting agents only) stops it acting."
        }
       ]
      },
      {
       "image": "/help/azure/17b-advanced-agents-more.png",
       "alt": "7.3 The Advanced pages (read-only) (17b-advanced-agents-more)",
       "keys": [
        {
         "n": 1,
         "text": "Watching agents — they only look and record; they cannot change anything."
        },
        {
         "n": 2,
         "text": "Each agent row opens to show what it may and may not do; Open goes to the screen it works through; Pause (acting agents only) stops it acting."
        }
       ]
      }
     ]
    }
   ]
  }
 ],
 "troubleshooting": [
  {
   "q": "Connect says it could not reach the namespace",
   "a": "Check the connection string was copied whole (it starts `Endpoint=sb://` and includes `SharedAccessKeyName` and `SharedAccessKey`). In the portal, open **Settings → Networking** and make sure public access is allowed from where ServiceHub runs. Confirm **Local Authentication** is *Enabled* on the Overview."
  },
  {
   "q": "Connect fails with 401 or says it could not list queues",
   "a": "The policy is missing **Manage**. Azure only lets Manage list queues and count messages. Create a policy with Manage (which includes Send and Listen) and connect again."
  },
  {
   "q": "Connect works but Replay is unavailable",
   "a": "Your policy lacks **Send**. Replay needs it. A policy with **Manage** includes Send and Listen, so create one as in step 1.3 and connect again."
  },
  {
   "q": "The counts differ from the portal",
   "a": "Portal metrics can lag by a minute. Press **Refresh** in ServiceHub and **Refresh** in the portal; they should agree."
  },
  {
   "q": "A message I replayed is not under Replayed",
   "a": "Check the time window on the Replayed tab (the default is the last 24 hours) and that the *Result* filter is *Any result*."
  }
 ]
}
