// GENERATED by scripts/docs-shots/build_guides.py from the guide spec and the screenshots' keys.json — do not edit by hand.
import type { Guide } from './types'

export const gcpGuide: Guide = {
 "cloud": "gcp",
 "title": "Google Pub/Sub",
 "sections": [
  {
   "part": "Part 1 — In the Google Cloud console",
   "steps": [
    {
     "title": "1.1 Look at your topics and subscriptions",
     "text": "Sign in to the Google Cloud console, pick your project (note its **Project ID**, not its name) and open **Pub/Sub**. **Topics** lists where messages are published; **Subscriptions** lists who reads them. A queue in ServiceHub is a subscription together with its topic.",
     "shots": [
      {
       "image": "/help/gcp/portal-01-topics.png",
       "alt": "1.1 Look at your topics and subscriptions (portal-01-topics)",
       "keys": [
        {
         "n": 1,
         "text": "Project picker — shows the project you are in. ServiceHub needs its Project ID, which is the part after projects/ in a topic's full name below (not the project's display name)."
        },
        {
         "n": 2,
         "text": "Topic IDs — where messages are published. ServiceHub finds every topic in the project; you do not list them."
        },
        {
         "n": 3,
         "text": "Topic name — the full path. The part after projects/ is your Project ID, the first thing you type into ServiceHub."
        }
       ]
      },
      {
       "image": "/help/gcp/portal-02-subscriptions.png",
       "alt": "1.1 Look at your topics and subscriptions (portal-02-subscriptions)",
       "keys": [
        {
         "n": 1,
         "text": "Subscription IDs — a queue in ServiceHub is a subscription together with its topic. The one ending -dlq-subscription holds your dead letters."
        },
        {
         "n": 2,
         "text": "Topic — the topic each subscription reads from."
        },
        {
         "n": 3,
         "text": "Ack deadline — how long a reader has to acknowledge a message before Pub/Sub delivers it again. ServiceHub hands a looked-at message straight back, so it never waits this out."
        }
       ]
      }
     ]
    },
    {
     "title": "1.2 Find the dead-letter policy",
     "text": "Open your main subscription and look at **Dead lettering**. It names the dead-letter topic and the **Maximum delivery attempts** — how many tries before Pub/Sub forwards a message there. The dead-letter topic needs its own subscription, or forwarded messages are not kept: that subscription is what ServiceHub reads as your dead letters.",
     "shots": [
      {
       "image": "/help/gcp/portal-03-subscription-dead-letter.png",
       "alt": "1.2 Find the dead-letter policy (portal-03-subscription-dead-letter)",
       "keys": [
        {
         "n": 1,
         "text": "Dead lettering — the tab for the same policy, where you can change it."
        },
        {
         "n": 2,
         "text": "Dead letter topic — where Pub/Sub forwards a message after it fails too often. ServiceHub reads this topic’s own subscription as your dead letters."
        },
        {
         "n": 3,
         "text": "Maximum delivery attempts — after this many failed tries Pub/Sub forwards the message. Reading a dead letter from ServiceHub counts as one more attempt, which is why ServiceHub only looks when you ask."
        }
       ]
      }
     ]
    },
    {
     "title": "1.3 Create a ServiceHub-only service account",
     "text": "Open **IAM & Admin → Service accounts → Create service account**. Name it (we use `servicehub-app`) and skip the optional role steps for now. Do not use your own account or the default compute account: a separate account can be switched off later without disturbing anything else.",
     "shots": [
      {
       "image": "/help/gcp/portal-04-service-accounts.png",
       "alt": "1.3 Create a ServiceHub-only service account (portal-04-service-accounts)",
       "keys": [
        {
         "n": 1,
         "text": "Create service account — start here to make an account just for ServiceHub, not your own."
        },
        {
         "n": 2,
         "text": "The ServiceHub account — separate from your own and from the accounts your applications use, so you can switch it off later without disturbing anything else."
        },
        {
         "n": 3,
         "text": "Status — Enabled. Disabling or deleting the account cuts ServiceHub off."
        }
       ]
      }
     ]
    },
    {
     "title": "1.4 Give it only the Pub/Sub roles it needs",
     "text": "Grant the three roles from the table at the start of this guide: **Pub/Sub Viewer** on the project (IAM page), and **Pub/Sub Subscriber** and **Pub/Sub Publisher** on your subscriptions and topics (each resource's **Permissions** panel) — or all three on the project if you prefer one step. If the key ever leaked, it could touch nothing outside Pub/Sub.",
     "shots": [
      {
       "image": "/help/gcp/portal-05-iam-roles.png",
       "alt": "1.4 Give it only the Pub/Sub roles it needs (portal-05-iam-roles)",
       "keys": [
        {
         "n": 1,
         "text": "Grant access — where you give an account a role on the whole project."
        },
        {
         "n": 2,
         "text": "The ServiceHub account with Pub/Sub Viewer on the project — it lets ServiceHub list your topics and subscriptions. Pub/Sub Subscriber and Pub/Sub Publisher are granted on the individual subscriptions and topics (next screenshot)."
        }
       ]
      },
      {
       "image": "/help/gcp/portal-06-topic-permissions.png",
       "alt": "1.4 Give it only the Pub/Sub roles it needs (portal-06-topic-permissions)",
       "keys": [
        {
         "n": 1,
         "text": "Add principal — grants a role on just this topic. Do the same on each subscription for Pub/Sub Subscriber."
        },
        {
         "n": 2,
         "text": "Pub/Sub Publisher — granted to the ServiceHub account on this topic only. It is used to put a replayed message back."
        },
        {
         "n": 3,
         "text": "Pub/Sub Viewer — inherited from the project, so the account can see this topic."
        }
       ]
      }
     ]
    },
    {
     "title": "1.5 Create a key",
     "text": "Open the service account, then **Keys → Add key → Create new key → JSON**. A file downloads — **Google shows its private key only once**. Treat the file like a password: ServiceHub encrypts it on arrival and never shows it again, but anyone who has it can use it. Disabling or deleting the key is how you revoke access later.",
     "shots": [
      {
       "image": "/help/gcp/portal-07-keys.png",
       "alt": "1.5 Create a key (portal-07-keys)",
       "keys": [
        {
         "n": 1,
         "text": "Google’s reminder that keys are a risk if they leak. Treat the file like a password, and delete the key when you no longer need it."
        },
        {
         "n": 2,
         "text": "Add key → Create new key → JSON — downloads the key file ServiceHub needs. Google shows the private key only once."
        },
        {
         "n": 3,
         "text": "The key — Active. The bin deletes it, which is how you revoke ServiceHub’s access later."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 2 — Connect Google Cloud in ServiceHub",
   "steps": [
    {
     "title": "2.1 The welcome page",
     "text": "With no cloud connected, ServiceHub opens on a welcome page. Choose **Connect Google**.",
     "shots": [
      {
       "image": "/help/gcp/01-welcome.png",
       "alt": "2.1 The welcome page (01-welcome)",
       "keys": [
        {
         "n": 1,
         "text": "Connect Google — opens the Add a cloud window on the Google Pub/Sub tab. It asks for a project ID and a service-account key file; nothing is read until you press Connect there."
        },
        {
         "n": 2,
         "text": "Add a cloud — the same window, from anywhere in the app. Use it later to connect Azure or AWS as well."
        },
        {
         "n": 3,
         "text": "Simple | Advanced — Simple is where you act. Advanced is read-only pages (ledger, signatures, agents); it never changes anything."
        },
        {
         "n": 4,
         "text": "Help — opens the Help panel with task-shaped answers and the keyboard shortcuts."
        },
        {
         "n": 5,
         "text": "Connect Azure / Connect AWS — the same Add a cloud window, on the Azure or AWS tab. You do not need them for Google Cloud."
        }
       ]
      }
     ]
    },
    {
     "title": "2.2 Add a cloud",
     "text": "The window opens on the Google Pub/Sub tab. Open **Where do I get the service-account key?** for the same console steps you just did.",
     "shots": [
      {
       "image": "/help/gcp/02-add-cloud.png",
       "alt": "2.2 Add a cloud (02-add-cloud)",
       "keys": [
        {
         "n": 1,
         "text": "Cloud tabs — Google Pub/Sub is selected. The Azure and AWS tabs ask for different credentials."
        },
        {
         "n": 2,
         "text": "Where do I get the service-account key? — expands the console steps, with the roles to give."
        },
        {
         "n": 3,
         "text": "Name — what you will see in ServiceHub. It is a label only; it does not change anything in Google Cloud."
        },
        {
         "n": 4,
         "text": "Environment — Development, UAT or Production. Start with Development; Auto Replay never acts in Production."
        },
        {
         "n": 5,
         "text": "Project ID — the ID (not the name or number) shown in the console’s project picker. ServiceHub reads the topics and subscriptions in this one project."
        },
        {
         "n": 6,
         "text": "Service-account key file — the JSON file you downloaded for the ServiceHub service account. It is read in your browser, encrypted on this server and never shown again."
        },
        {
         "n": 7,
         "text": "The roles ServiceHub uses — to watch, and (second sentence) also to replay. Give it nothing more."
        },
        {
         "n": 8,
         "text": "Cancel — closes the window; nothing is saved."
        },
        {
         "n": 9,
         "text": "Connect — tests the key, then saves it. It only lists topics and subscriptions; it never pulls, publishes or acknowledges anything by itself."
        },
        {
         "n": 10,
         "text": "(?) — opens Help on this very screen. Every window has one."
        },
        {
         "n": 11,
         "text": "✕ — closes the window without saving (Esc does the same)."
        }
       ]
      },
      {
       "image": "/help/gcp/02-add-cloud-help.png",
       "alt": "2.2 Add a cloud (02-add-cloud-help)",
       "keys": [
        {
         "n": 1,
         "text": "IAM & Admin → Service accounts — in the Google Cloud console, make an account just for ServiceHub (not your own)."
        },
        {
         "n": 2,
         "text": "Grant it only the Pub/Sub roles listed below, on the project you want watched."
        },
        {
         "n": 3,
         "text": "Keys → Add key → Create new key → JSON — a file downloads. Google shows its private key only once."
        },
        {
         "n": 4,
         "text": "Choose that file here, and type the Project ID shown on the console’s project picker."
        },
        {
         "n": 5,
         "text": "The form underneath — the cloud tabs, Name, Environment, Project ID and the key file, exactly as in the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "2.3 Fill it in and connect",
     "text": "Give it a name, keep the environment as **Development** for your first connection, type the **Project ID**, choose the key file you downloaded, and press **Connect**. ServiceHub reads the file in your browser, tests it, then saves it encrypted (AES-256-GCM).",
     "shots": [
      {
       "image": "/help/gcp/03-add-cloud-filled.png",
       "alt": "2.3 Fill it in and connect (03-add-cloud-filled)",
       "keys": [
        {
         "n": 1,
         "text": "A name you will recognise."
        },
        {
         "n": 2,
         "text": "The Project ID."
        },
        {
         "n": 3,
         "text": "The key file you chose. “Using …” confirms which file was read; its contents are never shown."
        },
        {
         "n": 4,
         "text": "Connect — tests the key, then saves it."
        },
        {
         "n": 5,
         "text": "The rest of the form — cloud tabs, Environment, the roles hint and Cancel, as described on the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "2.4 The result",
     "text": "You see what ServiceHub can see: how many topics and subscriptions it found, and that this cloud **cannot yet prove a replayed message stayed fixed** — ServiceHub will say so honestly rather than pretend.",
     "shots": [
      {
       "image": "/help/gcp/04-connected.png",
       "alt": "2.4 The result (04-connected)",
       "keys": [
        {
         "n": 1,
         "text": "The result: how many topics and subscriptions ServiceHub found, and whether this cloud can prove a replayed message stayed fixed (Google Cloud cannot yet — it will say so honestly)."
        },
        {
         "n": 2,
         "text": "Open Home — closes the window and shows Home."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 3 — Learn the screens",
   "steps": [
    {
     "title": "3.1 Home",
     "text": "Home answers: *what needs me* and *how is each cloud doing*. For Google Cloud it shows what the cloud can do (the chips: no message counts, recorded when you look, no browsing, can't confirm fixes yet), the **Look now** button, and what has been recorded. Scroll down for why messages failed, how replays ended, your subscriptions with a Look now beside each, the latest dead letters and a live activity list.",
     "shots": [
      {
       "image": "/help/gcp/05-home.png",
       "alt": "3.1 Home (05-home)",
       "keys": [
        {
         "n": 1,
         "text": "Window — the period Home counts over (24 hours, 7 or 30 days). It changes what you see, never what happens."
        },
        {
         "n": 2,
         "text": "Connected, and the project — ServiceHub can reach Google Cloud with your key; the project is the one you chose."
        },
        {
         "n": 3,
         "text": "What this cloud can do — the chips show what Google Cloud lets ServiceHub do safely. Pub/Sub reports no message counts, records dead letters only when you look, cannot browse messages, cannot prove a fix held and has no scheduled messages."
        },
        {
         "n": 4,
         "text": "Look now — asks Google Cloud for its dead letters (up to 100 per queue) and keeps them in ServiceHub. Every pull counts as a delivery attempt, which is why ServiceHub never does it on its own. It can take up to a minute per queue."
        },
        {
         "n": 5,
         "text": "Dead letters — opens the list of messages that failed and were set aside."
        },
        {
         "n": 6,
         "text": "Topics — opens your topics and subscriptions. Google Cloud reports no message counts, so there are none to show."
        },
        {
         "n": 7,
         "text": "Replayed — everything put back, by whom, and how it went."
        },
        {
         "n": 8,
         "text": "Auto Replay rules — opens the rules panel. On Google Cloud a rule always waits for a person, because Google Cloud cannot prove a fix held."
        },
        {
         "n": 9,
         "text": "Got it — hides this explanation. It does not affect your data."
        },
        {
         "n": 10,
         "text": "See all dead letters in Google Cloud — opens the Dead letters list for this cloud."
        },
        {
         "n": 11,
         "text": "Help for this page (the book beside the title) — opens Help on this very page, over it. Every page has one."
        }
       ]
      },
      {
       "image": "/help/gcp/05c-home-middle.png",
       "alt": "3.1 Home (05c-home-middle)",
       "keys": [
        {
         "n": 1,
         "text": "Why messages failed — the reasons among the dead letters ServiceHub has recorded, biggest first, with how many each has. It only counts what you have looked at."
        },
        {
         "n": 2,
         "text": "How replays ended — what happened to the replays in this window. On Google Cloud they stay “watching”, because Google Cloud cannot prove a fix held."
        },
        {
         "n": 3,
         "text": "Subscriptions — each subscription ServiceHub found, with a Look now → that records just that subscription’s dead letters. Google Cloud reports no message counts here."
        },
        {
         "n": 4,
         "text": "Latest recorded dead letters — the five most recent ServiceHub has recorded, each with Details →. “See all →” opens the full list."
        },
        {
         "n": 5,
         "text": "Recent activity — shown in full on the next screenshot."
        }
       ]
      },
      {
       "image": "/help/gcp/05d-home-end.png",
       "alt": "3.1 Home (05d-home-end)",
       "keys": [
        {
         "n": 1,
         "text": "The five latest dead letters, each with Details → — the same message view as on the Dead letters tab."
        },
        {
         "n": 2,
         "text": "Recent activity — what ServiceHub and people did, newest first (Live means it updates by itself). Each line opens to show its detail; nothing here changes anything."
        },
        {
         "n": 3,
         "text": "Why messages failed, and the subscriptions with their Look now → links — as on the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "3.2 The bar and the sidebar",
     "text": "These are the same on every page.",
     "shots": [
      {
       "image": "/help/gcp/05b-navigation.png",
       "alt": "3.2 The bar and the sidebar (05b-navigation)",
       "keys": [
        {
         "n": 1,
         "text": "Back — returns to the previous place in the app."
        },
        {
         "n": 2,
         "text": "Forward — goes to the place you came back from."
        },
        {
         "n": 3,
         "text": "Search (⌘K) — jump to a cloud, queue or page. Searching never changes anything."
        },
        {
         "n": 4,
         "text": "The bell — the only place the Agent asks you something. A number appears when it needs you."
        },
        {
         "n": 5,
         "text": "Simple — the two pages where you do the work."
        },
        {
         "n": 6,
         "text": "Advanced — four read-only pages."
        },
        {
         "n": 7,
         "text": "You — who ServiceHub records actions as, with your role."
        },
        {
         "n": 8,
         "text": "Dead letters — messages that failed, with the reason and a Replay button."
        },
        {
         "n": 9,
         "text": "Active messages — your topics and subscriptions (Google Cloud reports no message counts)."
        },
        {
         "n": 10,
         "text": "Replayed — what was put back and whether it stayed fixed."
        },
        {
         "n": 11,
         "text": "Auto Replay — rules for retries ServiceHub may do on its own."
        },
        {
         "n": 12,
         "text": "Your cloud — pick it to see only that cloud. The dot shows the connection is healthy."
        },
        {
         "n": 13,
         "text": "Connections — your connected clouds, to test or remove."
        },
        {
         "n": 14,
         "text": "Add a cloud — connect another cloud."
        },
        {
         "n": 15,
         "text": "Settings — connections, notifications, preferences, access and backup."
        },
        {
         "n": 16,
         "text": "Help — answers and shortcuts."
        },
        {
         "n": 17,
         "text": "Home — the overview: what needs attention, what the Agent is doing, and how replays ended."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 4 — Work with dead letters",
   "steps": [
    {
     "title": "4.1 The Dead letters tab",
     "text": "A **dead letter** is a message your consumer failed to process several times, so Pub/Sub forwarded it to the dead-letter topic. The list starts **empty on Google Cloud** even when messages are waiting, because pulling a message counts as a delivery attempt. Press **Look at Google Cloud's dead letters now**: ServiceHub pulls up to 100 per queue, records them, and hands them straight back. It never deletes or moves anything. It can take up to a minute per queue. Press it again to record more; Google Cloud hands back a sample, so a dead letter not seen on a later look stays in the list.",
     "shots": [
      {
       "image": "/help/gcp/06-dead-letters.png",
       "alt": "4.1 The Dead letters tab (06-dead-letters)",
       "keys": [
        {
         "n": 1,
         "text": "Namespace picker — all of Google Cloud, or one project."
        },
        {
         "n": 2,
         "text": "Why the list starts empty — on Google Cloud, reading a dead letter counts as one delivery attempt, so ServiceHub only looks when you ask. It reads up to 100 per queue and keeps them here; it can take up to a minute per queue."
        },
        {
         "n": 3,
         "text": "Look at Google Cloud’s dead letters now — receives up to 100 dead letters per queue, records them, and hands them straight back. It never deletes or moves anything; it does add one to each message’s delivery count."
        },
        {
         "n": 4,
         "text": "The empty list — “nothing recorded” does not mean there are none: the queue holds 324. Press Look now to see them."
        },
        {
         "n": 5,
         "text": "Help for this page — opens Help on this page’s step of the guide. The (?) beside it only re-shows the short explanation."
        },
        {
         "n": 6,
         "text": "The three tabs — Dead letters, Active and Replayed — switch the list below. The (?) beside the title brings back the short “What you’re looking at” card."
        },
        {
         "n": 7,
         "text": "Filters and Refresh — Showing, Time window, queue or topic and search narrow the list; Refresh re-reads what ServiceHub has recorded. On Google Cloud Refresh does not look at Google Cloud: only Look now does."
        }
       ]
      },
      {
       "image": "/help/gcp/06b-after-look.png",
       "alt": "4.1 The Dead letters tab (06b-after-look)",
       "keys": [
        {
         "n": 1,
         "text": "What the look found — when it ran, how many queues had dead letters, and how many new ones were recorded."
        },
        {
         "n": 2,
         "text": "Google Cloud hands back a sample, not the whole queue: a dead letter recorded earlier and not seen this time stays in the list; it is not assumed gone."
        },
        {
         "n": 3,
         "text": "Why they failed — Pub/Sub records no reason for a dead letter, so every one is counted as “No reason recorded”. The total is how many ServiceHub has recorded."
        },
        {
         "n": 4,
         "text": "Dead letters tab — the number is how many ServiceHub has recorded (Google Cloud does not report how many it holds)."
        },
        {
         "n": 5,
         "text": "Look again — records any dead letters not seen before. Each look adds one delivery attempt to the messages it reads."
        },
        {
         "n": 6,
         "text": "Reason chips — click one to show only that reason."
        },
        {
         "n": 7,
         "text": "The namespace picker, the (?) that re-shows the short explanation, and the Active and Replayed tabs."
        },
        {
         "n": 8,
         "text": "Filters, Replay All Messages and Refresh — described on the next screenshot, where the table is in view."
        },
        {
         "n": 9,
         "text": "The selection bar — the tick selects the whole page; View details chooses columns; Replay selected stays dimmed until something is ticked."
        },
        {
         "n": 10,
         "text": "The tick in the table heading — ticks every row on this page."
        },
        {
         "n": 11,
         "text": "The table headings — each has an ⓘ that explains that column in a sentence; the next screenshot shows the table itself."
        }
       ]
      }
     ]
    },
    {
     "title": "4.2 Filters, selection and the table",
     "text": "Narrow the list, tick the messages you want, and use **Details** or **Replay** on a row. Pub/Sub records no failure reason, so there is a single reason, *No reason recorded*; choosing it filters the list (with *show all reasons* at the foot to clear it), and the list pages at the bottom. Refresh re-reads what ServiceHub has recorded; only Look now asks Google Cloud.",
     "shots": [
      {
       "image": "/help/gcp/07-filters-and-table.png",
       "alt": "4.2 Filters, selection and the table (07-filters-and-table)",
       "keys": [
        {
         "n": 1,
         "text": "Showing — Stuck now, or messages that have since left the queue."
        },
        {
         "n": 2,
         "text": "Time window — only messages set aside in this period."
        },
        {
         "n": 3,
         "text": "Search — by message ID, queue, reason or error text."
        },
        {
         "n": 4,
         "text": "Replay All Messages — opens a preview of everything shown. Nothing is sent until you confirm the preview."
        },
        {
         "n": 5,
         "text": "Refresh — reads the queue again. It re-reads what ServiceHub has already recorded; it does not look at Google Cloud (only Look now does). The ⓘ beside it says when it was last updated."
        },
        {
         "n": 6,
         "text": "Selection — tick rows to act on several; this line shows how many."
        },
        {
         "n": 7,
         "text": "Replay selected — opens the same preview for just the ticked messages."
        },
        {
         "n": 8,
         "text": "Details — opens the message: why it failed, its body, properties and delivery history."
        },
        {
         "n": 9,
         "text": "Replay — opens the proposal for this one message. It does not send anything yet."
        },
        {
         "n": 10,
         "text": "The table — a tick on every row (the one in the heading ticks the whole page), Details and Replay on every row, and an ⓘ About button on each column heading that explains that column in a sentence. “View details” in the heading chooses which columns show."
        },
        {
         "n": 11,
         "text": "Reason chips — each shows a reason and how many messages have it. Click one to show only those; click it again to show all."
        },
        {
         "n": 12,
         "text": "All queues & topics — limit the list to one queue or topic."
        },
        {
         "n": 13,
         "text": "The selection bar — the tick selects every row on this page; View details chooses which columns show; Replay selected stays dimmed until something is ticked."
        },
        {
         "n": 14,
         "text": "Look at Google Cloud’s dead letters now — records any dead letters not seen before. Each look adds one delivery attempt to the messages it reads."
        }
       ]
      },
      {
       "image": "/help/gcp/07a-reason-filter.png",
       "alt": "4.2 Filters, selection and the table (07a-reason-filter)",
       "keys": [
        {
         "n": 1,
         "text": "Filtering by a reason — the chosen reason is highlighted and “show all reasons” clears the filter. The list below shows only that reason."
        },
        {
         "n": 2,
         "text": "The reason chips — click one to show only that reason."
        },
        {
         "n": 3,
         "text": "The namespace picker, the (?) that re-shows the short explanation, and the three tabs."
        },
        {
         "n": 4,
         "text": "Filters, Replay All Messages, Refresh and Look now — described on the earlier screenshots."
        },
        {
         "n": 5,
         "text": "The selection bar (which now offers “Select all” for this reason), the table headings and the rows, as on the earlier screenshots."
        }
       ]
      },
      {
       "image": "/help/gcp/07a-reason-filter-end.png",
       "alt": "4.2 Filters, selection and the table (07a-reason-filter-end)",
       "keys": [
        {
         "n": 1,
         "text": "Show all reasons — at the foot of a filtered list too: clears the reason filter and brings every recorded dead letter back."
        },
        {
         "n": 2,
         "text": "The rows of this reason only, and the selection bar repeated underneath."
        },
        {
         "n": 3,
         "text": "Paging — rows per page, previous, the page numbers and next."
        }
       ]
      },
      {
       "image": "/help/gcp/07c-table-end.png",
       "alt": "4.2 Filters, selection and the table (07c-table-end)",
       "keys": [
        {
         "n": 1,
         "text": "The foot of the table — the same ticks, Details and Replay on every row, and the selection bar repeated underneath."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next. The list holds up to 100 dead letters per queue from each look."
        }
       ]
      },
      {
       "image": "/help/gcp/07b-selection.png",
       "alt": "4.2 Filters, selection and the table (07b-selection)",
       "keys": [
        {
         "n": 1,
         "text": "Row tick — choose which messages to act on. The header tick chooses every row on the page."
        },
        {
         "n": 2,
         "text": "Selection count — how many messages are ticked."
        },
        {
         "n": 3,
         "text": "Clear — unticks everything. Nothing else changes."
        },
        {
         "n": 4,
         "text": "Replay selected — opens the bulk preview for just these messages. Nothing is sent yet."
        },
        {
         "n": 5,
         "text": "The tabs and the filter row — reason chips, Showing, Time window, queue, search, Replay All Messages and Refresh, each explained on the previous screenshot."
        },
        {
         "n": 6,
         "text": "The table — the ticks, Details and Replay on every row, and the whole-page tick in the heading."
        },
        {
         "n": 7,
         "text": "The selection bar — the whole-page tick and View details (which columns show)."
        }
       ]
      }
     ]
    },
    {
     "title": "4.3 Open a message",
     "text": "**Details** opens the message: *Reason not recorded* (Pub/Sub keeps none), a plain-words reading drawn from the message's own attributes (marked *Suggestion* because it is a reading, not something Google Cloud reported), and the body. The tabs show the body, the attributes your publisher attached, what Pub/Sub recorded, and delivery — which Google Cloud does not report, so it says so. At the bottom are **Replay this message** and **Purge instead…**, which only opens a form.",
     "shots": [
      {
       "image": "/help/gcp/08-message-details.png",
       "alt": "4.3 Open a message (08-message-details)",
       "keys": [
        {
         "n": 1,
         "text": "Expand — widens the panel for long messages."
        },
        {
         "n": 2,
         "text": "Overview — reason, why it failed, the body with the bad field marked."
        },
        {
         "n": 3,
         "text": "Delivery — what Google Cloud reports about delivery. It does not report how many times a message was tried, so this says so rather than guess."
        },
        {
         "n": 4,
         "text": "Why it failed — a plain-words reading of the recorded reason. Marked Suggestion: it is a reading, not something Google Cloud reported — Pub/Sub records no reason at all."
        },
        {
         "n": 5,
         "text": "Formatted / Raw — switch the body view."
        },
        {
         "n": 6,
         "text": "Replay this message — opens the proposal. Nothing is sent from here."
        },
        {
         "n": 7,
         "text": "Body, Properties and Headers — the other tabs; each is shown below."
        },
        {
         "n": 8,
         "text": "Formatted and Copy body — pretty-print the body, or copy it to your clipboard. The copy stays in your browser."
        },
        {
         "n": 9,
         "text": "Copy message ID — copies the ID so you can search for it elsewhere."
        }
       ]
      },
      {
       "image": "/help/gcp/08b-message-details-end.png",
       "alt": "4.3 Open a message (08b-message-details-end)",
       "keys": [
        {
         "n": 1,
         "text": "Replay this message — opens the proposal. Nothing is sent from here."
        },
        {
         "n": 2,
         "text": "Purge instead… — for a message not worth replaying. It only opens a small form: you give a reason, and nothing is deleted until you press “Purge for good”. Deleting is permanent, goes through the same checks as a replay, and is recorded with your name and reason."
        },
        {
         "n": 3,
         "text": "Expand, the body view and the copy buttons — as on the previous screenshots."
        }
       ]
      },
      {
       "image": "/help/gcp/08-message-details-body.png",
       "alt": "4.3 Open a message (08-message-details-body)",
       "keys": [
        {
         "n": 1,
         "text": "The message body exactly as it was sent."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        },
        {
         "n": 3,
         "text": "Formatted / Raw switch the view; Copy body copies it to your clipboard."
        }
       ]
      },
      {
       "image": "/help/gcp/08-message-details-properties.png",
       "alt": "4.3 Open a message (08-message-details-properties)",
       "keys": [
        {
         "n": 1,
         "text": "The attributes your publisher attached to the message (for example shs-error-type)."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      },
      {
       "image": "/help/gcp/08-message-details-headers.png",
       "alt": "4.3 Open a message (08-message-details-headers)",
       "keys": [
        {
         "n": 1,
         "text": "What Pub/Sub recorded: the message ID, the publish time and the subscription it was dead-lettered from."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      },
      {
       "image": "/help/gcp/08-message-details-delivery.png",
       "alt": "4.3 Open a message (08-message-details-delivery)",
       "keys": [
        {
         "n": 1,
         "text": "What Google Cloud reports about delivery. It does not report how many times a message was tried, so this says so rather than guess."
        },
        {
         "n": 2,
         "text": "Expand widens the panel; the other tabs (Overview, Body, Properties, Headers, Delivery) switch what is shown."
        }
       ]
      }
     ]
    },
    {
     "title": "4.4 Replay one message — you see the proposal first",
     "text": "**Replay** never sends straight away. It shows what will happen (the message is published back to the topic it came from and the dead-letter copy is removed once Google Cloud accepts the new one), every safety check, and what happens afterwards. Only the blue button sends. On Google Cloud finding the one message can take up to a minute.",
     "shots": [
      {
       "image": "/help/gcp/09-replay-proposal.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal)",
       "keys": [
        {
         "n": 1,
         "text": "The message — what is about to be replayed: ID, where it is stuck, when and why it was set aside, and its body."
        },
        {
         "n": 2,
         "text": "Replay 1 message — sends it back. It is only sent when you press this."
        },
        {
         "n": 3,
         "text": "What will happen, Safety checks, After it runs — fold open or closed; the next screenshot shows them open."
        },
        {
         "n": 4,
         "text": "Cancel — closes without sending."
        }
       ]
      },
      {
       "image": "/help/gcp/09-replay-proposal-middle.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal-middle)",
       "keys": [
        {
         "n": 1,
         "text": "The four sections of the proposal — The message, What will happen, Safety checks and After it runs. Each folds open or closed; nothing here sends anything."
        },
        {
         "n": 2,
         "text": "Replay 1 message sends it; Cancel closes without sending. Both are repeated at the foot of the window so they are always in reach."
        }
       ]
      },
      {
       "image": "/help/gcp/09-replay-proposal-checks.png",
       "alt": "4.4 Replay one message — you see the proposal first (09-replay-proposal-checks)",
       "keys": [
        {
         "n": 1,
         "text": "What will happen — where it goes and what happens to the dead-letter copy (it is removed once Google Cloud accepts the new one)."
        },
        {
         "n": 2,
         "text": "Safety checks — every check that must pass; a failing one blocks the replay and says why."
        },
        {
         "n": 3,
         "text": "After it runs — ServiceHub records it and watches for 24 hours; if it comes back, nothing retries it."
        },
        {
         "n": 4,
         "text": "Cancel — closes without sending."
        },
        {
         "n": 5,
         "text": "The folding headings and the Replay button repeated at the end of the window."
        }
       ]
      }
     ]
    },
    {
     "title": "4.5 Replay several at once",
     "text": "Tick messages (or use **Replay All Messages**) to get a preview: how many will be replayed, which are held back by a safety check, grouped by how they failed and where each goes. They are sent one at a time, each re-checked, and the run stops by itself after five sends in a row that are not accepted. Further down is **Purge instead…** — a separate, deliberate step to delete messages that are not worth replaying.",
     "shots": [
      {
       "image": "/help/gcp/13-bulk-replay.png",
       "alt": "4.5 Replay several at once (13-bulk-replay)",
       "keys": [
        {
         "n": 1,
         "text": "Preview — nothing has run yet. Step 1 of Preview → Run → Watch."
        },
        {
         "n": 2,
         "text": "Held back — messages that fail a safety check stay in dead letters; they are never forced."
        },
        {
         "n": 3,
         "text": "Grouped by how they failed — so you can see whether you are fixing one problem or several."
        },
        {
         "n": 4,
         "text": "Where each one goes — the queue each message will be sent back to."
        },
        {
         "n": 5,
         "text": "Replay N messages — sends them one at a time, re-checking each. You can stop partway."
        },
        {
         "n": 6,
         "text": "Cancel — nothing is sent."
        },
        {
         "n": 7,
         "text": "How it will run and After they are sent back — fold open to show the pace and the automatic stop (five sends in a row that are not accepted), and what ServiceHub does next."
        },
        {
         "n": 7,
         "text": "Page controls — move through the list when more messages are chosen than fit on one page."
        }
       ]
      },
      {
       "image": "/help/gcp/13b-bulk-replay-end.png",
       "alt": "4.5 Replay several at once (13b-bulk-replay-end)",
       "keys": [
        {
         "n": 1,
         "text": "How it will run — the pace (a few messages a second, gentle on your consumer) and the automatic stop: five sends in a row that are not accepted."
        },
        {
         "n": 2,
         "text": "After they are sent back — folds open to say what ServiceHub does next: it keeps watching, and on Google Cloud it records each one as “verification required”, never as fixed."
        },
        {
         "n": 3,
         "text": "Purge instead… — for messages not worth replaying. It does not delete anything yet: it opens a separate step that asks why, shows what would be purged, and needs you to type a confirmation. Deleting is for good, and each purge is recorded with your name and reason."
        },
        {
         "n": 4,
         "text": "Page controls — move through the list when more messages are chosen than fit on one page."
        },
        {
         "n": 5,
         "text": "Replay N messages — sends them one at a time, re-checking each. You can stop partway."
        },
        {
         "n": 6,
         "text": "Cancel — nothing is sent."
        },
        {
         "n": 7,
         "text": "Where each one goes — folds open to show the queue each message is sent back to."
        }
       ]
      }
     ]
    },
    {
     "title": "4.6 The result",
     "text": "ServiceHub says plainly what happened and records it under Replayed. On Google Cloud the result will read **Verification required**: the message was sent back, but Google Cloud cannot prove the dead-letter queue stayed empty, so ServiceHub never says it held. If a consumer is running on the subscription it may pick the message up straight away.",
     "shots": [
      {
       "image": "/help/gcp/10-replay-result.png",
       "alt": "4.6 The result (10-replay-result)",
       "keys": [
        {
         "n": 1,
         "text": "The result, in plain words: it was sent back, and ServiceHub will watch for it coming back."
        },
        {
         "n": 2,
         "text": "It is recorded, with who did it, and shows under Replayed (and in Advanced → Recovery Ledger). On Google Cloud the result will read “Verification required”: this cloud cannot prove the queue stayed empty, so ServiceHub never says it held."
        },
        {
         "n": 3,
         "text": "Done — closes the window."
        },
        {
         "n": 4,
         "text": "Active messages / Replayed — jump to where you can watch this message."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 5 — Afterwards",
   "steps": [
    {
     "title": "5.1 Replayed",
     "text": "Every replay, who did it, and how it ended. On Google Cloud a replay stays *Watching* for its window and is then recorded as *verification required* — never as success — until a person judges it.",
     "shots": [
      {
       "image": "/help/gcp/11-replayed.png",
       "alt": "5.1 Replayed (11-replayed)",
       "keys": [
        {
         "n": 1,
         "text": "Messages replayed — how many were put back in the window."
        },
        {
         "n": 2,
         "text": "Being watched — replays still inside their watch window. Google Cloud cannot prove whether each stayed fixed, so they wait for you to judge."
        },
        {
         "n": 3,
         "text": "Came back — messages that failed the same way again. Nothing retries them on its own."
        },
        {
         "n": 4,
         "text": "Result filter — stayed fixed, being watched, came back."
        },
        {
         "n": 5,
         "text": "Download — saves this list as a file. It does not change anything."
        },
        {
         "n": 6,
         "text": "Details — the full record of this replay."
        },
        {
         "n": 7,
         "text": "Filters — namespace, queue or topic, result, time window and search; Refresh reads the list again. They change what is listed, never what happened."
        },
        {
         "n": 8,
         "text": "The table — a tick per replay (the heading tick ticks the page) and Details on each row."
        },
        {
         "n": 9,
         "text": "What am I looking at? — a short reading guide. Auto Replay rules — opens the rules page. All and Last 24 hours — the result and time filters."
        },
        {
         "n": 10,
         "text": "The three tabs — Dead letters, Active and Replayed. They switch the list below without leaving the page."
        }
       ]
      },
      {
       "image": "/help/gcp/11b-replayed-end.png",
       "alt": "5.1 Replayed (11b-replayed-end)",
       "keys": [
        {
         "n": 1,
         "text": "The replays, newest first — each with a tick and Details."
        },
        {
         "n": 2,
         "text": "Paging — rows per page, previous, the page numbers and next."
        },
        {
         "n": 3,
         "text": "Filters — result, queue or topic, who replayed it, time window and search; Refresh re-reads the list and Download as CSV saves it as a file. They change what is listed, never what happened."
        },
        {
         "n": 4,
         "text": "The three tabs, the Auto Replay rules button and the table headings, as on the previous screenshot."
        }
       ]
      }
     ]
    },
    {
     "title": "5.2 Active messages",
     "text": "Your topics and subscriptions. Pub/Sub reports **no message counts**, so each says *can't count here* rather than guess. ServiceHub does not open active messages on Google Cloud, because there is no way to look at one without it counting as a delivery — watching could push a message into the dead-letter topic by itself. For the same reason **Follow live** is not offered here. **Send a message** is the one control here that changes a topic.",
     "shots": [
      {
       "image": "/help/gcp/12-active.png",
       "alt": "5.2 Active messages (12-active)",
       "keys": [
        {
         "n": 1,
         "text": "Send a message — puts a test message on a queue. This does change the queue, so use a dev queue."
        },
        {
         "n": 2,
         "text": "Why there is no message list — on Google Cloud there is no way to look at a message without it counting as a delivery, and watching could push it into the dead-letter queue by itself. So ServiceHub shows counts per queue, and “Follow live” is not offered."
        },
        {
         "n": 3,
         "text": "Namespace — all of AWS, or one account and region."
        },
        {
         "n": 4,
         "text": "The three tabs — Dead letters, Active and Replayed — and the (?) that re-shows the short explanation."
        },
        {
         "n": 5,
         "text": "The table — one row per topic and subscription: Queue or topic, Waiting now and Dead-lettered. Pub/Sub reports no counts, so the counts say “can’t count here” rather than guess; the ⓘ on each heading says what the column means."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 6 — Auto Replay",
   "steps": [
    {
     "title": "6.1 Rules",
     "text": "A rule names a failure ServiceHub has already seen and how carefully to retry it. It never runs in Production, goes through the same safety checks as you, and **stops itself** if fewer than half of its replays stay fixed. On Google Cloud a rule always waits for a person, because Google Cloud cannot prove a fix held.",
     "shots": [
      {
       "image": "/help/gcp/14-auto-replay.png",
       "alt": "6.1 Rules (14-auto-replay)",
       "keys": [
        {
         "n": 1,
         "text": "Auto Generate Rules — proposes rules from failures already seen. It only proposes; you decide what to turn on."
        },
        {
         "n": 2,
         "text": "Create rule — start a rule from a failure you have already seen."
        },
        {
         "n": 3,
         "text": "How it works — you name a failure, safety checks decide, it replays gently, it proves it worked and stops itself if it does not."
        },
        {
         "n": 4,
         "text": "Totals — rules on, replayed by rules, waiting for a person, stopped themselves."
        },
        {
         "n": 5,
         "text": "Namespace — Auto Replay rules apply to every Google Cloud project you connected; this picks which one the page shows."
        },
        {
         "n": 6,
         "text": "Refresh rules — reads the rules again."
        },
        {
         "n": 7,
         "text": "Create your first rule — the same as Create rule, shown while there are none."
        }
       ]
      },
      {
       "image": "/help/gcp/14-auto-replay-create.png",
       "alt": "6.1 Rules (14-auto-replay-create)",
       "keys": [
        {
         "n": 1,
         "text": "Based on — pick a failure ServiceHub has already seen. A rule can only be made from a seen failure."
        },
        {
         "n": 2,
         "text": "The guarantees: never in Production, same safety checks as you, and it stops itself if fewer than half stay fixed."
        },
        {
         "n": 3,
         "text": "Create and turn on — enabled once you choose a failure."
        },
        {
         "n": 4,
         "text": "Cancel — nothing is created."
        },
        {
         "n": 5,
         "text": "The page header — namespace, Refresh rules, Auto Generate Rules (proposes only) and the “How Auto Replay works” fold, as on the previous screenshot."
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "part": "Part 7 — Settings, Help and Advanced",
   "steps": [
    {
     "title": "7.1 Settings",
     "text": "Connections, Notifications (Slack, Teams, any webhook — sent only when the Agent stops and needs a person), Preferences, Access & security (roles and the emergency stop) and Backup.",
     "shots": [
      {
       "image": "/help/gcp/15-settings-connections.png",
       "alt": "7.1 Settings (15-settings-connections)",
       "keys": [
        {
         "n": 1,
         "text": "Sections — Connections, Notifications, Preferences, Access & security and Backup. Each jumps to that part of this window."
        },
        {
         "n": 2,
         "text": "Add a cloud — connect another cloud."
        },
        {
         "n": 3,
         "text": "Test — checks the connection now and shows the result. Reads only."
        },
        {
         "n": 4,
         "text": "Remove — forgets this connection and its stored credential. It does not delete anything in Google Cloud."
        }
       ]
      },
      {
       "image": "/help/gcp/15-settings-notifications.png",
       "alt": "7.1 Settings (15-settings-notifications)",
       "keys": [
        {
         "n": 1,
         "text": "In-app bell and pop-up — always on. It cannot be switched off, so it can never be switched off by mistake."
        },
        {
         "n": 2,
         "text": "Add webhook (Slack) — paste a Slack incoming-webhook URL to also get the message there."
        },
        {
         "n": 3,
         "text": "Add webhook (Microsoft Teams) — the same for a Teams channel."
        },
        {
         "n": 4,
         "text": "Add webhook (any other system) — JSON to a URL you choose. Private and internal addresses are refused."
        }
       ]
      },
      {
       "image": "/help/gcp/15-settings-preferences.png",
       "alt": "7.1 Settings (15-settings-preferences)",
       "keys": [
        {
         "n": 1,
         "text": "Theme — Light today; Dark is marked soon."
        },
        {
         "n": 2,
         "text": "Times shown in — your browser’s time zone, or UTC. It changes how times are displayed, never the data."
        },
        {
         "n": 3,
         "text": "Open on — start in Simple every time (Simple), or where you last were (Last used). Kept in this browser only."
        }
       ]
      },
      {
       "image": "/help/gcp/15-settings-access.png",
       "alt": "7.1 Settings (15-settings-access)",
       "keys": [
        {
         "n": 1,
         "text": "Who you are — shown from this browser session until roles are switched on. The credential key fingerprint shows what encrypts stored credentials."
        },
        {
         "n": 2,
         "text": "Roles — Viewer sees, Operator replays, Approver answers the Agent, Admin connects clouds. Giving the first role switches roles on."
        },
        {
         "n": 3,
         "text": "Who — the API key name or signed-in user the role is for."
        },
        {
         "n": 4,
         "text": "Kind, Role, Where and Grant — choose whether it is a key or a person, the role, whether it applies everywhere or to one namespace, then Grant. Granting the first role switches roles on for everyone."
        },
        {
         "n": 5,
         "text": "Emergency stop — type STOP, say why, and switch it on to halt every automatic action at once. Nothing already done is undone; switch it off to resume."
        }
       ]
      },
      {
       "image": "/help/gcp/15-settings-backup.png",
       "alt": "7.1 Settings (15-settings-backup)",
       "keys": [
        {
         "n": 1,
         "text": "Take a backup now — saves a consistent copy of ServiceHub’s own database (not of your clouds)."
        }
       ]
      }
     ]
    },
    {
     "title": "7.2 Help, search and the bell",
     "text": "Help is a panel over whatever you are doing. Search (⌘K) jumps anywhere. The bell is the only place the Agent asks you something.",
     "shots": [
      {
       "image": "/help/gcp/16-help.png",
       "alt": "7.2 Help, search and the bell (16-help)",
       "keys": [
        {
         "n": 1,
         "text": "Search — type what you are trying to do."
        },
        {
         "n": 2,
         "text": "An answer — click to open it in place; each links to the screen it is about."
        },
        {
         "n": 3,
         "text": "Setting up answers — connecting, alerts and who may replay."
        },
        {
         "n": 4,
         "text": "Keyboard shortcuts — only ones that work are listed."
        },
        {
         "n": 5,
         "text": "Step by step — one guide per cloud, each with every screen as a real screenshot and a numbered key for every button and link. Yours (Google Cloud) is listed first. The same guides are the articles in docs/clouds."
        }
       ]
      },
      {
       "image": "/help/gcp/16b-help-end.png",
       "alt": "7.2 Help, search and the bell (16b-help-end)",
       "keys": [
        {
         "n": 1,
         "text": "Answers and guides — click one to open it in place; the “Every screen” entries are one guide per cloud, each a real screenshot with a numbered key for every button and link."
        }
       ]
      },
      {
       "image": "/help/gcp/18-search.png",
       "alt": "7.2 Help, search and the bell (18-search)",
       "keys": [
        {
         "n": 1,
         "text": "Search box — type part of a cloud, queue or page name. Enter opens the first result. Esc closes. Searching never changes anything."
        }
       ]
      },
      {
       "image": "/help/gcp/18-bell.png",
       "alt": "7.2 Help, search and the bell (18-bell)",
       "keys": [
        {
         "n": 1,
         "text": "The bell — the only place the Agent asks you something. It lists what is waiting for you and clears when it is resolved, not when you look."
        },
        {
         "n": 2,
         "text": "See all waiting — opens the full list of what needs a person."
        }
       ]
      }
     ]
    },
    {
     "title": "7.3 The Advanced pages (read-only)",
     "text": "Advanced never changes anything. **Overview** summarises recovery, authority and agents, and says why Google Cloud cannot verify; the **Recovery Ledger** is the tamper-evident record of every action; **Failure Signatures** groups failures (on Google Cloud, with no reason recorded, they group by subscription); **Agents** lists what is acting and what is only watching.",
     "shots": [
      {
       "image": "/help/gcp/17-advanced-overview.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-overview)",
       "keys": [
        {
         "n": 1,
         "text": "Scope — all clouds, or one."
        },
        {
         "n": 2,
         "text": "Window — the period the page counts over."
        },
        {
         "n": 3,
         "text": "Insights — patterns ServiceHub noticed across your failures."
        },
        {
         "n": 4,
         "text": "Recovery — how replays ended. “Recovered” means it did not come back, not that the business transaction completed."
        },
        {
         "n": 5,
         "text": "Authority — what each failure may do on its own, and what holds it there."
        },
        {
         "n": 6,
         "text": "Capability — what each cloud can prove."
        },
        {
         "n": 7,
         "text": "Being watched, All agents → and Recovery Ledger → — jump to the Agents page and the Recovery Ledger. They only open pages; nothing changes."
        },
        {
         "n": 8,
         "text": "Overview — the page you are on; the other three Advanced pages are in the bar at the top."
        },
        {
         "n": 9,
         "text": "Why → — explains why this cloud cannot yet prove a replayed message stayed fixed, and what would unlock it. It opens Help; nothing changes."
        }
       ]
      },
      {
       "image": "/help/gcp/17-advanced-ledger.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-ledger)",
       "keys": [
        {
         "n": 1,
         "text": "Export evidence — downloads the ledger so it can be verified offline. It changes nothing."
        },
        {
         "n": 2,
         "text": "Outcome chips — Waiting, Watching, Recovered, Unverified, Returned, Failed, Unknown, Declined. Recovered and Unverified are never counted together."
        },
        {
         "n": 3,
         "text": "Filters — cloud, namespace, queue or topic, who did it, and search."
        },
        {
         "n": 4,
         "text": "Details — who took the action, what happened and its evidence. Each entry carries a fingerprint of the one before it."
        },
        {
         "n": 5,
         "text": "Filters and entries — namespace, queue or topic, who, and search narrow the list; each entry opens to show its evidence."
        },
        {
         "n": 6,
         "text": "What am I looking at? — a short reading guide for this page. Window — the period it counts over."
        },
        {
         "n": 7,
         "text": "Outcome chips with counts — click one to list only those entries; All shows everything again."
        },
        {
         "n": 8,
         "text": "Paging — how many rows per page, previous, the page number and next."
        },
        {
         "n": 9,
         "text": "The table headings — each has an ⓘ that explains that column in a sentence."
        }
       ]
      },
      {
       "image": "/help/gcp/17-advanced-signatures.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-signatures)",
       "keys": [
        {
         "n": 1,
         "text": "Trace a message — follow one message across clouds by its ID."
        },
        {
         "n": 2,
         "text": "Growing — signatures whose recent days hold at least twice what earlier days did."
        },
        {
         "n": 3,
         "text": "Sort — most messages, or others."
        },
        {
         "n": 4,
         "text": "A signature — one way of failing: the same queue and the same kind of error, so many messages become one thing to reason about."
        },
        {
         "n": 5,
         "text": "Replays — how many of these were replayed and how many were verified to have held. On Google Cloud none can be verified, and this says so."
        },
        {
         "n": 6,
         "text": "Filters — cloud, namespace, queue or topic, who, and search."
        },
        {
         "n": 7,
         "text": "Each signature row — opens to show the failures grouped under it and what each replay did."
        },
        {
         "n": 8,
         "text": "What am I looking at? — a short reading guide. Window — the period counted."
        },
        {
         "n": 9,
         "text": "Chips — Signatures, All, Replay helps, Replay doesn’t help. Click one to list only those."
        },
        {
         "n": 10,
         "text": "Paging — rows per page, previous, the page number and next."
        },
        {
         "n": 11,
         "text": "The table headings — Signature, Messages, Days and Replays, each with an ⓘ that explains it."
        }
       ]
      },
      {
       "image": "/help/gcp/17-advanced-agents.png",
       "alt": "7.3 The Advanced pages (read-only) (17-advanced-agents)",
       "keys": [
        {
         "n": 1,
         "text": "Acting agents — the only ones that can change anything, and only after the same safety checks you get."
        },
        {
         "n": 2,
         "text": "Watching agents — they only look and record."
        },
        {
         "n": 3,
         "text": "Pause — stops that agent acting. It is the one thing Advanced can do, because it only removes authority. Nothing it already did is undone."
        },
        {
         "n": 4,
         "text": "Learn more — a short explanation of how agents work."
        },
        {
         "n": 5,
         "text": "Health summary, agent rows and Open — the summary says whether every agent is running normally; a row opens that agent’s details; Open goes to the screen the agent works through."
        },
        {
         "n": 6,
         "text": "What am I looking at? — a short reading guide for this page."
        }
       ]
      },
      {
       "image": "/help/gcp/17b-advanced-agents-more.png",
       "alt": "7.3 The Advanced pages (read-only) (17b-advanced-agents-more)",
       "keys": [
        {
         "n": 1,
         "text": "Watching agents — they only look and record; they cannot change anything."
        },
        {
         "n": 2,
         "text": "Each agent row opens to show what it may and may not do; Open goes to the screen it works through; Pause (acting agents only) stops it acting."
        },
        {
         "n": 3,
         "text": "Learn more — a short explanation of how agents work."
        }
       ]
      }
     ]
    }
   ]
  }
 ],
 "troubleshooting": [
  {
   "q": "Connect says the key is invalid, or could not authenticate",
   "a": "Check you chose the whole JSON file the console downloaded for the ServiceHub service account (it contains `\"type\": \"service_account\"` and a `private_key`), and that the key is still **Enabled** (IAM & Admin → Service accounts → the account → Keys). A key cannot be downloaded again: if you lost the file, create a new key."
  },
  {
   "q": "Connect works but finds no topics or subscriptions",
   "a": "Check the **Project ID** — it is the ID, not the project name or number — and that the service account has **Pub/Sub Viewer** on that project."
  },
  {
   "q": "Creating the key is blocked",
   "a": "Your organisation may enforce the policy *Disable service account key creation* (`iam.disableServiceAccountKeyCreation`). Ask an administrator for an exception for this project, or use a project where it is allowed."
  },
  {
   "q": "Dead letters stays empty after Look now",
   "a": "The dead-letter subscription may really be empty, or there may be no subscription on the dead-letter topic (forwarded messages are dropped without one), or the service account lacks **Pub/Sub Subscriber** on it."
  },
  {
   "q": "Replay is unavailable or refused",
   "a": "The service account lacks **Pub/Sub Publisher** on the topic (to put the copy back) or **Pub/Sub Subscriber** on the subscription (to remove the dead-letter copy)."
  },
  {
   "q": "Look now or Replay takes a long time",
   "a": "Pub/Sub has no way to fetch one message by id, so ServiceHub pulls until it finds it; with a long dead-letter queue this can take up to a minute. Keep the window open — nothing is lost if you leave."
  },
  {
   "q": "The counts say “can't count here”",
   "a": "Pub/Sub reports no message counts to ServiceHub. That is the cloud, not a fault: ServiceHub shows what it has recorded instead."
  },
  {
   "q": "Why does every replay say “Verification required”?",
   "a": "ServiceHub can prove a fix held only where the cloud can show the dead-letter queue stayed empty. Google Cloud cannot, so ServiceHub records the replay honestly instead of calling it fixed."
  }
 ]
}
