// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceHub.Infrastructure.Persistence;

#nullable disable

namespace ServiceHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServiceHubDbContext))]
    [Migration("0002_W2_DlqMessages")]
    partial class W2_DlqMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ServiceHub.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("OwnerId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Timestamp");

                    b.HasIndex("OwnerId", "NamespaceId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Namespace_Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.DlqMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationPropertiesJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPreview")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterErrorDescription")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnqueuedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionCause")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyHash")
                        .HasDatabaseName("IX_DlqMessages_BodyHash");

                    b.HasIndex("DetectedAtUtc")
                        .HasDatabaseName("IX_DlqMessages_DetectedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "Status")
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Status");

                    b.HasIndex("OwnerId", "NamespaceId", "EntityName", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Entity_Sequence");

                    b.ToTable("DlqMessages", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.Namespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsRegion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("TEXT")
                        .HasColumnName("ConnectionStringEncrypted");

                    b.Property<string>("ConnectionStringHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GcpProjectId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastConnectionTestAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastConnectionTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Namespaces_IsActive");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Namespaces_OwnerId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_OwnerId_Name");

                    b.ToTable("Namespaces", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
