// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceHub.Infrastructure.Persistence;

#nullable disable

namespace ServiceHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ServiceHubDbContext))]
    [Migration("0008_W4_AutonomyGrants")]
    partial class W4_AutonomyGrants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ServiceHub.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("OwnerId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Timestamp");

                    b.HasIndex("OwnerId", "NamespaceId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Namespace_Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutoReplayRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AskedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackOff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledDetail")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAskedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAskedReason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Provider", "Enabled")
                        .HasDatabaseName("IX_AutoReplayRules_Owner_Provider_Enabled");

                    b.ToTable("AutoReplayRules", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutonomyGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "SignatureHash", "ActionKind")
                        .IsUnique()
                        .HasDatabaseName("IX_AutonomyGrants_Owner_SignatureHash_ActionKind");

                    b.ToTable("AutonomyGrants", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.BulkOperationItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecoveryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remedy")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Position")
                        .HasDatabaseName("IX_BulkOperationItems_Job_Position");

                    b.ToTable("BulkOperationItems", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.BulkOperationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndedReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("PerSecond")
                        .HasColumnType("REAL");

                    b.Property<string>("PreviewedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SampleOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("StopAfterConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("IX_BulkOperationJobs_Owner_Status");

                    b.ToTable("BulkOperationJobs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.DlqMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationPropertiesJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPreview")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterErrorDescription")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnqueuedTimeUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionCause")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyHash")
                        .HasDatabaseName("IX_DlqMessages_BodyHash");

                    b.HasIndex("DetectedAtUtc")
                        .HasDatabaseName("IX_DlqMessages_DetectedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash")
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Signature");

                    b.HasIndex("OwnerId", "NamespaceId", "Status")
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Status");

                    b.HasIndex("OwnerId", "NamespaceId", "EntityName", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Entity_Sequence");

                    b.ToTable("DlqMessages", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.Namespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsRegion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("TEXT")
                        .HasColumnName("ConnectionStringEncrypted");

                    b.Property<string>("ConnectionStringHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GcpProjectId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastConnectionTestAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastConnectionTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Namespaces_IsActive");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Namespaces_OwnerId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_OwnerId_Name");

                    b.ToTable("Namespaces", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.NamespaceSignature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DominantDeadletterReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopTermsJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash")
                        .IsUnique()
                        .HasDatabaseName("IX_NamespaceSignatures_Owner_Namespace_Hash");

                    b.ToTable("NamespaceSignatures", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.RecoveryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "Seq")
                        .HasDatabaseName("IX_RecoveryEvents_EntryId_Seq");

                    b.HasIndex("OperationId", "Seq")
                        .HasDatabaseName("IX_RecoveryEvents_OperationId_Seq");

                    b.HasIndex("OwnerId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("IX_RecoveryEvents_Owner_Seq");

                    b.HasIndex("OwnerId", "EventType", "Seq")
                        .HasDatabaseName("IX_RecoveryEvents_Owner_EventType_Seq");

                    b.ToTable("RecoveryEvents", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.RecoveryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BegunAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterReasonSnapshot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTypeSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategorySnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEventSeq")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MarkerApplied")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationWindowEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryMarker")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHashSnapshot")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMessageIdSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceSequenceNumberSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationConfidence")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationResult")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("IX_RecoveryLedgerEntries_OperationId");

                    b.HasIndex("RecoveryMarker")
                        .IsUnique()
                        .HasDatabaseName("IX_RecoveryLedgerEntries_RecoveryMarker")
                        .HasFilter("[RecoveryMarker] IS NOT NULL");

                    b.HasIndex("OwnerId", "State", "BegunAt")
                        .HasDatabaseName("IX_RecoveryLedgerEntries_Owner_State_BegunAt");

                    b.HasIndex("OwnerId", "NamespaceId", "EntityNameSnapshot", "BodyHash")
                        .HasDatabaseName("IX_RecoveryLedgerEntries_Owner_Namespace_Entity_BodyHash");

                    b.ToTable("RecoveryLedgerEntries", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.RecoveryOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorScopes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentHeader")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceJobId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "OpenedAt")
                        .HasDatabaseName("IX_RecoveryOperations_Owner_OpenedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "OpenedAt")
                        .HasDatabaseName("IX_RecoveryOperations_Owner_Namespace_OpenedAt");

                    b.ToTable("RecoveryOperations", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.ReplayHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecoveryEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayStrategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedToEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DlqMessageId")
                        .HasDatabaseName("IX_ReplayHistories_DlqMessageId");

                    b.HasIndex("ReplayedAt")
                        .HasDatabaseName("IX_ReplayHistories_ReplayedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "ReplayedAt")
                        .HasDatabaseName("IX_ReplayHistories_Owner_Namespace_ReplayedAt");

                    b.ToTable("ReplayHistories", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.BulkOperationItem", b =>
                {
                    b.HasOne("ServiceHub.Core.Entities.BulkOperationJob", null)
                        .WithMany("Items")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.BulkOperationJob", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
