// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceHub.Infrastructure.Persistence;

#nullable disable

namespace ServiceHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DlqDbContext))]
    [Migration("20260829202111_AddExternalSignalEvents")]
    partial class AddExternalSignalEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ServiceHub.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("OwnerId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Timestamp");

                    b.HasIndex("OwnerId", "NamespaceId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Namespace_Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutoReplayRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReasonDetail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReplaysPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId");

                    b.ToTable("AutoReplayRules", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutonomyGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "SignatureHash", "ActionKind")
                        .IsUnique()
                        .HasDatabaseName("IX_AutonomyGrants_Owner_SignatureHash_ActionKind");

                    b.ToTable("AutonomyGrants", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.BulkOperationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryFilter")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityNameFilter")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureSampleJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FromFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedByActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByScopes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusFilter")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ToFilter")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BulkOperationJobs_Status");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("IX_BulkOperationJobs_Owner_CreatedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "CreatedAt")
                        .HasDatabaseName("IX_BulkOperationJobs_Owner_Namespace_CreatedAt");

                    b.ToTable("BulkOperationJobs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.DlqMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationPropertiesJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPreview")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<double>("CategoryConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Azure");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterErrorDescription")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeadLetterTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("ForensicConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("ForensicRootCause")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplaySafety")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ReplaySuccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionCause")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyHash")
                        .HasDatabaseName("IX_DlqMessages_BodyHash");

                    b.HasIndex("DetectedAtUtc")
                        .HasDatabaseName("IX_DlqMessages_DetectedAt");

                    b.HasIndex("FailureCategory")
                        .HasDatabaseName("IX_DlqMessages_FailureCategory");

                    b.HasIndex("OwnerId", "NamespaceId", "Status")
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Status");

                    b.HasIndex("OwnerId", "NamespaceId", "EntityName", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Entity_Sequence");

                    b.ToTable("DlqMessages", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.ExternalSignalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId", "OccurredAt")
                        .HasDatabaseName("IX_ExternalSignalEvents_OwnerId_NamespaceId_OccurredAt");

                    b.ToTable("ExternalSignalEvents", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.FailureKnowledgeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("KnowledgeVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayGuidance")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCause")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunbookLink")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewDueAt")
                        .HasDatabaseName("IX_FailureKnowledge_ReviewDueAt");

                    b.HasIndex("OwnerId", "NamespaceId")
                        .HasDatabaseName("IX_FailureKnowledge_Owner_Namespace");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash")
                        .IsUnique()
                        .HasDatabaseName("IX_FailureKnowledge_Owner_Namespace_SignatureHash");

                    b.ToTable("FailureKnowledge", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.FailureKnowledgeHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnowledgeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayGuidance")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootCause")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunbookLink")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash", "KnowledgeVersion")
                        .HasDatabaseName("IX_FailureKnowledgeHistory_Owner_Namespace_SignatureHash_Version");

                    b.ToTable("FailureKnowledgeHistory", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.GovernanceGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedByIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GranteeIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GranteeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PillarKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedByIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "GranteeIdentity")
                        .HasDatabaseName("IX_GovernanceGrants_OwnerId_GranteeIdentity");

                    b.HasIndex("OwnerId", "NamespaceId")
                        .HasDatabaseName("IX_GovernanceGrants_OwnerId_NamespaceId");

                    b.HasIndex("OwnerId", "GranteeIdentity", "NamespaceId", "PillarKind")
                        .IsUnique()
                        .HasDatabaseName("IX_GovernanceGrants_ActiveScope_Unique")
                        .HasFilter("[RevokedAt] IS NULL");

                    b.ToTable("GovernanceGrants", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.MessageFeatureRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BodySizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeadletterReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorTextNormalised")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadShape")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("SecondsSinceEnqueued")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeToDeadletterSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DlqMessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_MessageFeatureRecords_DlqMessageId");

                    b.HasIndex("NamespaceId", "CapturedAt")
                        .HasDatabaseName("IX_MessageFeatureRecords_Namespace_CapturedAt");

                    b.HasIndex("NamespaceId", "EntityName")
                        .HasDatabaseName("IX_MessageFeatureRecords_Namespace_EntityName");

                    b.ToTable("MessageFeatureRecords", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.Namespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsRegion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("TEXT")
                        .HasColumnName("ConnectionStringEncrypted");

                    b.Property<string>("ConnectionStringHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("GcpProjectId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasListenPermission")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasManagePermission")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSendPermission")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastConnectionTestAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastConnectionTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Namespaces_IsActive");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Namespaces_OwnerId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Namespaces_OwnerId_Name");

                    b.ToTable("Namespaces", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.NamespaceSharedOwner", b =>
                {
                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("NamespaceId", "OwnerId");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_NamespaceSharedOwners_OwnerId");

                    b.ToTable("NamespaceSharedOwners", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.NamespaceSignature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DominantDeadletterReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopTermsJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId")
                        .HasDatabaseName("IX_NamespaceSignatures_Owner_Namespace");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash")
                        .IsUnique()
                        .HasDatabaseName("IX_NamespaceSignatures_Owner_Namespace_SignatureHash");

                    b.ToTable("NamespaceSignatures", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.PlaybookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceRefJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEventSeq")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PillarKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProposedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposerIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSnapshot")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedRecoveryOperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHashSnapshot")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId")
                        .HasDatabaseName("IX_PlaybookEntries_OwnerId_NamespaceId");

                    b.HasIndex("OwnerId", "PillarKind")
                        .HasDatabaseName("IX_PlaybookEntries_OwnerId_PillarKind");

                    b.HasIndex("OwnerId", "State")
                        .HasDatabaseName("IX_PlaybookEntries_OwnerId_State");

                    b.ToTable("PlaybookEntries", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.PlaybookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "Seq")
                        .HasDatabaseName("IX_PlaybookEvents_EntryId_Seq");

                    b.HasIndex("OwnerId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("IX_PlaybookEvents_OwnerId_Seq");

                    b.ToTable("PlaybookEvents", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.RecoveryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "Seq")
                        .HasDatabaseName("IX_RecoveryEvents_EntryId_Seq");

                    b.HasIndex("OperationId", "Seq")
                        .HasDatabaseName("IX_RecoveryEvents_OperationId_Seq");

                    b.HasIndex("OwnerId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("IX_RecoveryEvents_Owner_Seq");

                    b.HasIndex("OwnerId", "EventType", "Seq")
                        .HasDatabaseName("IX_RecoveryEvents_Owner_EventType_Seq");

                    b.ToTable("RecoveryEvents", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.RecoveryLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BegunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterReasonSnapshot")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTypeSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategorySnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("LastEventSeq")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MarkerApplied")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ObservationWindowEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryMarker")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHashSnapshot")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMessageIdSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceSequenceNumberSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicNameSnapshot")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationConfidence")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationResult")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("IX_RecoveryLedgerEntries_OperationId");

                    b.HasIndex("RecoveryMarker")
                        .IsUnique()
                        .HasDatabaseName("IX_RecoveryLedgerEntries_RecoveryMarker")
                        .HasFilter("[RecoveryMarker] IS NOT NULL");

                    b.HasIndex("OwnerId", "State", "BegunAt")
                        .HasDatabaseName("IX_RecoveryLedgerEntries_Owner_State_BegunAt");

                    b.HasIndex("OwnerId", "NamespaceId", "EntityNameSnapshot", "BodyHash")
                        .HasDatabaseName("IX_RecoveryLedgerEntries_Owner_Namespace_Entity_BodyHash");

                    b.ToTable("RecoveryLedgerEntries", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.RecoveryOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorScopes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentHeader")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceNameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSnapshot")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceJobId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "OpenedAt")
                        .HasDatabaseName("IX_RecoveryOperations_Owner_OpenedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "OpenedAt")
                        .HasDatabaseName("IX_RecoveryOperations_Owner_Namespace_OpenedAt");

                    b.ToTable("RecoveryOperations", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.ReplayHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayStrategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedToEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DlqMessageId")
                        .HasDatabaseName("IX_ReplayHistories_DlqMessageId");

                    b.HasIndex("ReplayedAt")
                        .HasDatabaseName("IX_ReplayHistories_ReplayedAt");

                    b.HasIndex("RuleId");

                    b.ToTable("ReplayHistories", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.SignatureLifecycleHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash", "Timestamp")
                        .HasDatabaseName("IX_SignatureLifecycleHistory_Owner_Namespace_SignatureHash_Timestamp");

                    b.ToTable("SignatureLifecycleHistory", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.SignatureLifecycleState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransitionedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash")
                        .IsUnique()
                        .HasDatabaseName("IX_SignatureLifecycleStates_Owner_Namespace_SignatureHash");

                    b.ToTable("SignatureLifecycleStates", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.SignatureReplayJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureSampleJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FromFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedByActorKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByScopes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusFilter")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ToFilter")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SignatureReplayJobs_Status");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash", "CreatedAt")
                        .HasDatabaseName("IX_SignatureReplayJobs_Owner_Namespace_SignatureHash_CreatedAt");

                    b.ToTable("SignatureReplayJobs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.MessageFeatureRecord", b =>
                {
                    b.HasOne("ServiceHub.Core.Entities.DlqMessage", "DlqMessage")
                        .WithOne("FeatureRecord")
                        .HasForeignKey("ServiceHub.Core.Entities.MessageFeatureRecord", "DlqMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DlqMessage");
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.NamespaceSharedOwner", b =>
                {
                    b.HasOne("ServiceHub.Core.Entities.Namespace", null)
                        .WithMany()
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.ReplayHistory", b =>
                {
                    b.HasOne("ServiceHub.Core.Entities.DlqMessage", "DlqMessage")
                        .WithMany("ReplayHistories")
                        .HasForeignKey("DlqMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceHub.Core.Entities.AutoReplayRule", "Rule")
                        .WithMany("ReplayHistories")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DlqMessage");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutoReplayRule", b =>
                {
                    b.Navigation("ReplayHistories");
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.DlqMessage", b =>
                {
                    b.Navigation("FeatureRecord");

                    b.Navigation("ReplayHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
