// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceHub.Infrastructure.Persistence;

#nullable disable

namespace ServiceHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DlqDbContext))]
    [Migration("20260727094238_AddNamespaceSignatures")]
    partial class AddNamespaceSignatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ServiceHub.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudProvider")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("OwnerId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Timestamp");

                    b.HasIndex("OwnerId", "NamespaceId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Owner_Namespace_Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutoReplayRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReplaysPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutoReplayRules", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.BulkOperationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryFilter")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityNameFilter")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureSampleJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FromFilter")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusFilter")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ToFilter")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BulkOperationJobs_Status");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("IX_BulkOperationJobs_Owner_CreatedAt");

                    b.HasIndex("OwnerId", "NamespaceId", "CreatedAt")
                        .HasDatabaseName("IX_BulkOperationJobs_Owner_Namespace_CreatedAt");

                    b.ToTable("BulkOperationJobs", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.DlqMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationPropertiesJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPreview")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<double>("CategoryConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Azure");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterErrorDescription")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeadLetterTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("ForensicConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("ForensicRootCause")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("MessageSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplaySafety")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ReplaySuccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyHash")
                        .HasDatabaseName("IX_DlqMessages_BodyHash");

                    b.HasIndex("DetectedAtUtc")
                        .HasDatabaseName("IX_DlqMessages_DetectedAt");

                    b.HasIndex("FailureCategory")
                        .HasDatabaseName("IX_DlqMessages_FailureCategory");

                    b.HasIndex("OwnerId", "NamespaceId", "Status")
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Status");

                    b.HasIndex("OwnerId", "NamespaceId", "EntityName", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_DlqMessages_Owner_Namespace_Entity_Sequence");

                    b.ToTable("DlqMessages", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.MessageFeatureRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BodySizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeadletterReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorTextNormalised")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadShape")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("SecondsSinceEnqueued")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeToDeadletterSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DlqMessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_MessageFeatureRecords_DlqMessageId");

                    b.HasIndex("NamespaceId", "CapturedAt")
                        .HasDatabaseName("IX_MessageFeatureRecords_Namespace_CapturedAt");

                    b.HasIndex("NamespaceId", "EntityName")
                        .HasDatabaseName("IX_MessageFeatureRecords_Namespace_EntityName");

                    b.ToTable("MessageFeatureRecords", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.NamespaceSignature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DominantDeadletterReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TopTermsJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "NamespaceId")
                        .HasDatabaseName("IX_NamespaceSignatures_Owner_Namespace");

                    b.HasIndex("OwnerId", "NamespaceId", "SignatureHash")
                        .IsUnique()
                        .HasDatabaseName("IX_NamespaceSignatures_Owner_Namespace_SignatureHash");

                    b.ToTable("NamespaceSignatures", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.ReplayHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DlqMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDeadLetterReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayStrategy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReplayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplayedToEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DlqMessageId")
                        .HasDatabaseName("IX_ReplayHistories_DlqMessageId");

                    b.HasIndex("ReplayedAt")
                        .HasDatabaseName("IX_ReplayHistories_ReplayedAt");

                    b.HasIndex("RuleId");

                    b.ToTable("ReplayHistories", (string)null);
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.MessageFeatureRecord", b =>
                {
                    b.HasOne("ServiceHub.Core.Entities.DlqMessage", "DlqMessage")
                        .WithOne("FeatureRecord")
                        .HasForeignKey("ServiceHub.Core.Entities.MessageFeatureRecord", "DlqMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DlqMessage");
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.ReplayHistory", b =>
                {
                    b.HasOne("ServiceHub.Core.Entities.DlqMessage", "DlqMessage")
                        .WithMany("ReplayHistories")
                        .HasForeignKey("DlqMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceHub.Core.Entities.AutoReplayRule", "Rule")
                        .WithMany("ReplayHistories")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DlqMessage");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.AutoReplayRule", b =>
                {
                    b.Navigation("ReplayHistories");
                });

            modelBuilder.Entity("ServiceHub.Core.Entities.DlqMessage", b =>
                {
                    b.Navigation("FeatureRecord");

                    b.Navigation("ReplayHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
