import { describe, it, expect } from 'vitest';

/**
 * Test the incident report format generation logic
 * (extracted from PropertiesTab component)
 */
function generateReport(message: {
  id: string;
  queueType: string;
  enqueuedTime: Date;
  deliveryCount: number;
  deadLetterReason?: string;
  deadLetterSource?: string;
  body?: string;
}, queueName: string, correlationId?: string): string {
  const lines = [
    '## Message Incident Report',
    `**Generated by ServiceHub** · ${new Date().toISOString()}`,
    '',
    '| Field | Value |',
    '|---|---|',
    `| Message ID | ${message.id} |`,
    `| Queue/Entity | ${queueName} |`,
    `| Enqueued | ${message.enqueuedTime ? new Date(message.enqueuedTime).toISOString() : '-'} |`,
    `| Delivery Count | ${message.deliveryCount} |`,
    `| State | ${message.queueType} |`,
  ];
  if (message.deadLetterReason) {
    lines.push(`| DLQ Reason | ${message.deadLetterReason} |`);
  }
  if (message.deadLetterSource) {
    lines.push(`| DLQ Description | ${message.deadLetterSource} |`);
  }
  if (correlationId) {
    lines.push(`| Correlation ID | ${correlationId} |`);
  }
  lines.push('', '**Body Preview:**', '', message.body ? message.body.substring(0, 500) : '-');
  lines.push('', '**Tool:** https://app-servicehub-prod.azurewebsites.net');
  return lines.join('\n');
}

describe('Incident Report Format', () => {
  const baseMessage = {
    id: 'msg-abc-123',
    queueType: 'deadletter',
    enqueuedTime: new Date('2025-03-15T12:00:00Z'),
    deliveryCount: 5,
    body: '{"orderId": "ORD-123", "status": "failed"}',
  };

  it('contains the message ID', () => {
    const report = generateReport(baseMessage, 'orders-queue');
    expect(report).toContain('msg-abc-123');
  });

  it('contains the entity name', () => {
    const report = generateReport(baseMessage, 'orders-queue');
    expect(report).toContain('orders-queue');
  });

  it('contains DLQ reason when present', () => {
    const msg = { ...baseMessage, deadLetterReason: 'MaxDeliveryCountExceeded' };
    const report = generateReport(msg, 'orders-queue');
    expect(report).toContain('MaxDeliveryCountExceeded');
    expect(report).toContain('DLQ Reason');
  });

  it('does not contain DLQ reason row when absent', () => {
    const report = generateReport(baseMessage, 'orders-queue');
    expect(report).not.toContain('DLQ Reason');
  });

  it('contains the ServiceHub URL', () => {
    const report = generateReport(baseMessage, 'orders-queue');
    expect(report).toContain('https://app-servicehub-prod.azurewebsites.net');
  });

  it('contains correlation ID when present', () => {
    const report = generateReport(baseMessage, 'orders-queue', 'corr-xyz-789');
    expect(report).toContain('corr-xyz-789');
    expect(report).toContain('Correlation ID');
  });

  it('truncates body to 500 chars', () => {
    const longBody = 'x'.repeat(1000);
    const msg = { ...baseMessage, body: longBody };
    const report = generateReport(msg, 'orders-queue');
    // Body should be truncated
    const bodySection = report.split('**Body Preview:**')[1];
    expect(bodySection).toBeDefined();
    // The body in the report should be at most 500 chars of 'x'
    const xCount = (bodySection!.match(/x/g) || []).length;
    expect(xCount).toBe(500);
  });

  it('contains the report header', () => {
    const report = generateReport(baseMessage, 'orders-queue');
    expect(report).toContain('## Message Incident Report');
    expect(report).toContain('**Generated by ServiceHub**');
  });
});
